/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 05 22:22:11 GMT 2018
 */

package com.polimi.travlendar.backend.model.user;

import org.junit.Test;
import static org.junit.Assert.*;
import com.polimi.travlendar.backend.model.user.Notification;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Notification_ESTest extends Notification_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Notification notification0 = new Notification("k7H)");
      String string0 = notification0.getMessage();
      assertEquals("k7H)", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Notification notification0 = new Notification("");
      String string0 = notification0.getMessage();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Notification notification0 = new Notification((String) null);
      String string0 = notification0.getMessage();
      assertNull(string0);
  }
}
