/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 04 11:12:02 GMT 2018
 */

package com.polimi.travlendar.gmaps;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.google.maps.model.AutocompletePrediction;
import com.polimi.travlendar.gmaps.DefaultCaptionGenerator;
import com.polimi.travlendar.gmaps.DynamicList;
import com.polimi.travlendar.gmaps.PlaceSearchField;
import com.polimi.travlendar.gmaps.SelectionListener;
import com.vaadin.ui.ItemCaptionGenerator;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DynamicList_ESTest extends DynamicList_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PlaceSearchField placeSearchField0 = new PlaceSearchField();
      DynamicList dynamicList0 = new DynamicList((SelectionListener) placeSearchField0, 572);
      // Undeclared exception!
      try { 
        dynamicList0.setList((List<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PlaceSearchField placeSearchField0 = new PlaceSearchField();
      DefaultCaptionGenerator defaultCaptionGenerator0 = new DefaultCaptionGenerator();
      DynamicList dynamicList0 = new DynamicList((SelectionListener) placeSearchField0, 0, (ItemCaptionGenerator) defaultCaptionGenerator0);
      assertEquals(1, dynamicList0.getComponentCount());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PlaceSearchField placeSearchField0 = new PlaceSearchField();
      AutocompletePrediction[] autocompletePredictionArray0 = new AutocompletePrediction[6];
      // Undeclared exception!
      try { 
        placeSearchField0.deliverPredictions(autocompletePredictionArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.polimi.travlendar.gmaps.PredictionCaptionGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PlaceSearchField placeSearchField0 = new PlaceSearchField();
      AutocompletePrediction[] autocompletePredictionArray0 = new AutocompletePrediction[0];
      placeSearchField0.deliverPredictions(autocompletePredictionArray0);
      assertTrue(placeSearchField0.isVisible());
  }
}
