/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 04 11:29:23 GMT 2018
 */

package com.polimi.travlendar.payment.checkout;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.polimi.travlendar.payment.checkout.ChargeController;
import com.polimi.travlendar.payment.checkout.ChargeRequest;
import com.stripe.exception.StripeException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.springframework.ui.Model;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ChargeController_ESTest extends ChargeController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ChargeController chargeController0 = new ChargeController();
      // Undeclared exception!
      try { 
        chargeController0.handleError((Model) null, (StripeException) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.polimi.travlendar.payment.checkout.ChargeController", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ChargeController chargeController0 = new ChargeController();
      // Undeclared exception!
      try { 
        chargeController0.charge((ChargeRequest) null, (Model) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.polimi.travlendar.payment.checkout.ChargeController", e);
      }
  }
}
