/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 05 22:24:33 GMT 2018
 */

package com.polimi.travlendar.backend.model.events;

import org.junit.Test;
import static org.junit.Assert.*;
import com.polimi.travlendar.backend.model.events.Meeting;
import com.polimi.travlendar.backend.model.user.PreferenceLevel;
import java.time.ZonedDateTime;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Meeting_ESTest extends Meeting_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Meeting meeting0 = new Meeting(true);
      boolean boolean0 = meeting0.isLongTimeEvent();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Meeting meeting0 = new Meeting(true);
      boolean boolean0 = meeting0.isLongTime();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Meeting meeting0 = new Meeting(true);
      meeting0.setUser((-1L));
      long long0 = meeting0.getUser();
      assertEquals((-1L), long0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Meeting meeting0 = new Meeting(false);
      Meeting.State meeting_State0 = Meeting.State.started;
      meeting0.setState(meeting_State0);
      meeting0.getState();
      assertFalse(meeting0.isLongTimeEvent());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Meeting meeting0 = new Meeting(false);
      meeting0.setStartingLocation("i_<gR* `");
      meeting0.getStartingLocation();
      assertFalse(meeting0.isLongTimeEvent());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Meeting meeting0 = new Meeting(false);
      meeting0.setStartingLocation("");
      meeting0.getStartingLocation();
      assertFalse(meeting0.isLongTime());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Meeting meeting0 = new Meeting(false);
      PreferenceLevel preferenceLevel0 = PreferenceLevel.MEDIUM;
      meeting0.setLevel(preferenceLevel0);
      meeting0.getPreferenceLevel();
      assertFalse(meeting0.isLongTime());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Meeting meeting0 = new Meeting(true);
      meeting0.setName("MEDIUM");
      meeting0.getName();
      assertTrue(meeting0.isLongTimeEvent());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Meeting meeting0 = new Meeting(true);
      meeting0.setName("");
      meeting0.getName();
      assertTrue(meeting0.isLongTime());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Meeting meeting0 = new Meeting(false);
      meeting0.setStartingLocation("-Ay<+R4*%X1");
      meeting0.getLocation();
      assertFalse(meeting0.isLongTimeEvent());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Meeting meeting0 = new Meeting(false);
      PreferenceLevel preferenceLevel0 = PreferenceLevel.LOW;
      meeting0.setPreferenceLevel(preferenceLevel0);
      meeting0.getLevel();
      assertFalse(meeting0.isLongTimeEvent());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Meeting meeting0 = new Meeting(true);
      meeting0.setId(1L);
      long long0 = meeting0.getId();
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Meeting meeting0 = new Meeting(false);
      meeting0.setId((-203L));
      long long0 = meeting0.getId();
      assertEquals((-203L), long0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Meeting meeting0 = new Meeting(true);
      meeting0.setEndingLocation("HIGH");
      meeting0.getEndingLocation();
      assertTrue(meeting0.isLongTimeEvent());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Meeting meeting0 = new Meeting(true);
      meeting0.setEndingLocation("");
      meeting0.getEndingLocation();
      assertTrue(meeting0.isLongTime());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Meeting meeting0 = new Meeting(true);
      meeting0.setDuration(1252L);
      long long0 = meeting0.getDuration();
      assertEquals(1252L, long0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Meeting meeting0 = new Meeting(true);
      meeting0.setDuration((-1375L));
      long long0 = meeting0.getDuration();
      assertEquals((-1375L), long0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Meeting meeting0 = new Meeting(true);
      meeting0.setDetails("planned");
      meeting0.getDetails();
      assertTrue(meeting0.isLongTime());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Meeting meeting0 = new Meeting(true);
      meeting0.setDetails("");
      meeting0.getDetails();
      assertTrue(meeting0.isLongTimeEvent());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Meeting meeting0 = new Meeting(false);
      meeting0.getLevel();
      assertFalse(meeting0.isLongTimeEvent());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Meeting meeting0 = new Meeting(true);
      meeting0.getEnd();
      assertTrue(meeting0.isLongTimeEvent());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Meeting meeting0 = new Meeting(false);
      meeting0.setLocation("");
      assertFalse(meeting0.isLongTimeEvent());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Meeting meeting0 = new Meeting(false);
      boolean boolean0 = meeting0.isLongTime();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Meeting meeting0 = new Meeting(true);
      meeting0.getId();
      assertTrue(meeting0.isLongTimeEvent());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Meeting meeting0 = new Meeting(false);
      meeting0.getStart();
      assertFalse(meeting0.isLongTimeEvent());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Meeting meeting0 = new Meeting(true);
      boolean boolean0 = meeting0.isEditable();
      assertTrue(meeting0.isLongTime());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Meeting meeting0 = new Meeting(true);
      meeting0.getName();
      assertTrue(meeting0.isLongTime());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Meeting meeting0 = new Meeting(true);
      meeting0.setEnd((ZonedDateTime) null);
      assertTrue(meeting0.isLongTimeEvent());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Meeting meeting0 = new Meeting(true);
      meeting0.getEndingLocation();
      assertTrue(meeting0.isLongTimeEvent());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Meeting meeting0 = new Meeting(false);
      meeting0.getPreferenceLevel();
      assertFalse(meeting0.isLongTimeEvent());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Meeting meeting0 = new Meeting(false);
      boolean boolean0 = meeting0.isLongTimeEvent();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Meeting meeting0 = new Meeting(false);
      meeting0.getState();
      assertFalse(meeting0.isLongTimeEvent());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Meeting meeting0 = new Meeting(false);
      meeting0.getStartingLocation();
      assertFalse(meeting0.isLongTimeEvent());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Meeting meeting0 = new Meeting(false);
      meeting0.setStartingLocation("");
      meeting0.getLocation();
      assertFalse(meeting0.isLongTime());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Meeting meeting0 = new Meeting(false);
      meeting0.getDuration();
      assertFalse(meeting0.isLongTime());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Meeting meeting0 = new Meeting(false);
      meeting0.setUser(1967L);
      long long0 = meeting0.getUser();
      assertEquals(1967L, long0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Meeting meeting0 = new Meeting(false);
      meeting0.getLocation();
      assertFalse(meeting0.isLongTime());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Meeting meeting0 = new Meeting(true);
      meeting0.setStart((ZonedDateTime) null);
      assertTrue(meeting0.isLongTimeEvent());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Meeting meeting0 = new Meeting(false);
      meeting0.setLongTime(false);
      assertFalse(meeting0.isLongTime());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Meeting meeting0 = new Meeting(false);
      meeting0.getUser();
      assertFalse(meeting0.isLongTimeEvent());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Meeting meeting0 = new Meeting(true);
      meeting0.getDetails();
      assertTrue(meeting0.isLongTimeEvent());
  }
}
