/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 05 22:15:09 GMT 2018
 */

package com.polimi.travlendar.backend.model.events;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.MockitoExtension.*;
import com.polimi.travlendar.backend.model.events.Meeting;
import com.polimi.travlendar.backend.model.events.OnEventClick;
import com.vaadin.server.Sizeable;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class OnEventClick_ESTest extends OnEventClick_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Meeting meeting0 = mock(Meeting.class, new ViolatedAssumptionAnswer());
      OnEventClick onEventClick0 = new OnEventClick(meeting0);
      assertEquals(Sizeable.Unit.PIXELS, onEventClick0.getHeightUnits());
  }
}
