/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Jan 04 11:26:26 GMT 2018
 */

package com.polimi.travlendar.backend.database;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class TrainTicketRowMapper_ESTest_scaffolding {

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);

  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.polimi.travlendar.backend.database.TrainTicketRowMapper"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init(); 
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("java.vm.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.specification.version", "1.8"); 
            java.lang.System.setProperty("java.home", "/usr/lib/jvm/java-8-oracle/jre"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("user.home", "/home/jaycaves"); 
                                        java.lang.System.setProperty("user.dir", "/home/jaycaves/Desktop/FumagalliGrottiGullo/Implementation"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("awt.toolkit", "sun.awt.X11.XToolkit"); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("file.separator", "/"); 
        java.lang.System.setProperty("java.awt.graphicsenv", "sun.awt.X11GraphicsEnvironment"); 
    java.lang.System.setProperty("java.awt.printerjob", "sun.print.PSPrinterJob"); 
    java.lang.System.setProperty("java.class.path", "/tmp/EvoSuite_pathingJar770778466667948572.jar"); 
    java.lang.System.setProperty("java.class.version", "52.0"); 
        java.lang.System.setProperty("java.endorsed.dirs", "/usr/lib/jvm/java-8-oracle/jre/lib/endorsed"); 
    java.lang.System.setProperty("java.ext.dirs", "/usr/lib/jvm/java-8-oracle/jre/lib/ext:/usr/java/packages/lib/ext"); 
    java.lang.System.setProperty("java.library.path", "lib"); 
    java.lang.System.setProperty("java.runtime.name", "Java(TM) SE Runtime Environment"); 
    java.lang.System.setProperty("java.runtime.version", "1.8.0_131-b11"); 
    java.lang.System.setProperty("java.specification.name", "Java Platform API Specification"); 
    java.lang.System.setProperty("java.specification.vendor", "Oracle Corporation"); 
        java.lang.System.setProperty("java.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vendor.url", "http://java.oracle.com/"); 
    java.lang.System.setProperty("java.version", "1.8.0_131"); 
    java.lang.System.setProperty("java.vm.info", "mixed mode"); 
    java.lang.System.setProperty("java.vm.name", "Java HotSpot(TM) 64-Bit Server VM"); 
    java.lang.System.setProperty("java.vm.specification.name", "Java Virtual Machine Specification"); 
    java.lang.System.setProperty("java.vm.specification.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vm.specification.version", "1.8"); 
    java.lang.System.setProperty("java.vm.version", "25.131-b11"); 
    java.lang.System.setProperty("line.separator", "\n"); 
    java.lang.System.setProperty("os.arch", "amd64"); 
    java.lang.System.setProperty("os.name", "Linux"); 
    java.lang.System.setProperty("os.version", "4.10.0-42-generic"); 
    java.lang.System.setProperty("path.separator", ":"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "jaycaves"); 
    java.lang.System.setProperty("user.timezone", "Europe/Rome"); 
      }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(TrainTicketRowMapper_ESTest_scaffolding.class.getClassLoader() ,
      "com.polimi.fakePTS.tickets.TicketType",
      "com.mysql.jdbc.Util$RandStructcture",
      "com.mysql.jdbc.MultiHostConnectionProxy",
      "com.mysql.jdbc.PreparedStatement",
      "com.mysql.jdbc.exceptions.MySQLNonTransientConnectionException",
      "com.mysql.jdbc.Util",
      "com.mysql.fabric.jdbc.FabricMySQLDriver",
      "com.mysql.jdbc.Extension",
      "com.mysql.jdbc.AbandonedConnectionCleanupThread$1",
      "com.mysql.jdbc.MysqlDataTruncation",
      "org.hsqldb.jdbc.JDBCDriver",
      "com.mysql.jdbc.Field",
      "com.mysql.jdbc.AbandonedConnectionCleanupThread",
      "com.mysql.jdbc.CommunicationsException",
      "com.mysql.jdbc.StatementImpl",
      "org.hsqldb.jdbc.JDBCDriver$1",
      "com.mysql.jdbc.CachedResultSetMetaData",
      "com.mysql.jdbc.exceptions.DeadlockTimeoutRollbackMarker",
      "com.polimi.travlendar.backend.database.TrainTicketRowMapper",
      "com.mysql.jdbc.ConnectionProperties",
      "com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException",
      "com.mysql.jdbc.Connection",
      "com.mysql.jdbc.NotUpdatable",
      "com.mysql.jdbc.StringUtils$SearchMode",
      "com.mysql.jdbc.Driver",
      "com.mysql.jdbc.ResultSetRow",
      "com.mysql.jdbc.SingleByteCharsetConverter",
      "com.mysql.jdbc.NotImplemented",
      "org.springframework.jdbc.core.RowMapper",
      "com.mysql.jdbc.SQLError",
      "com.mysql.jdbc.exceptions.MySQLNonTransientException",
      "com.mysql.jdbc.JDBC42ResultSet",
      "com.mysql.jdbc.JDBC4UpdatableResultSet",
      "com.mysql.jdbc.exceptions.jdbc4.CommunicationsException",
      "com.mysql.jdbc.exceptions.MySQLQueryInterruptedException",
      "com.mysql.jdbc.StringUtils",
      "com.mysql.jdbc.RowData",
      "com.polimi.fakePTS.tickets.Ticket",
      "com.mysql.jdbc.ResultSetImpl",
      "com.mysql.jdbc.exceptions.MySQLTransientException",
      "com.mysql.jdbc.JDBC42UpdatableResultSet",
      "com.polimi.fakePTS.RandomTicketId",
      "com.mysql.jdbc.MySQLConnection",
      "com.mysql.jdbc.UpdatableResultSet",
      "com.mysql.jdbc.Messages",
      "com.mysql.jdbc.exceptions.MySQLDataException",
      "com.mysql.jdbc.StreamingNotifiable",
      "com.mysql.jdbc.ResultSetInternalMethods",
      "com.mysql.jdbc.exceptions.MySQLTransactionRollbackException",
      "com.mysql.jdbc.Wrapper",
      "com.mysql.jdbc.exceptions.MySQLSyntaxErrorException",
      "com.mysql.jdbc.Statement",
      "com.polimi.fakePTS.tickets.TrainTicket",
      "com.mysql.jdbc.NonRegisteringDriver",
      "com.mysql.jdbc.JDBC4ResultSet",
      "com.mysql.jdbc.ByteArrayRow",
      "com.mysql.jdbc.exceptions.MySQLTransientConnectionException",
      "com.mysql.jdbc.ExceptionInterceptor"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(TrainTicketRowMapper_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.polimi.fakePTS.tickets.TicketType",
      "com.mysql.jdbc.Messages",
      "com.mysql.jdbc.Util",
      "com.mysql.jdbc.StringUtils$SearchMode",
      "com.mysql.jdbc.StringUtils",
      "com.mysql.jdbc.UpdatableResultSet",
      "com.mysql.jdbc.ResultSetImpl",
      "com.polimi.fakePTS.RandomTicketId",
      "com.mysql.jdbc.exceptions.jdbc4.CommunicationsException",
      "com.mysql.jdbc.SQLError",
      "com.mysql.jdbc.AbandonedConnectionCleanupThread",
      "com.mysql.jdbc.NonRegisteringDriver",
      "com.mysql.jdbc.Driver",
      "com.mysql.fabric.jdbc.FabricMySQLDriver",
      "org.hsqldb.jdbc.JDBCDriver",
      "com.mysql.jdbc.NotUpdatable"
    );
  }
}
