/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 05 22:16:40 GMT 2018
 */

package com.polimi.travlendar.backend.database;

import org.junit.Test;
import static org.junit.Assert.*;
import com.polimi.travlendar.backend.database.TrainTicketRowMapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TrainTicketRowMapper_ESTest extends TrainTicketRowMapper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TrainTicketRowMapper trainTicketRowMapper0 = new TrainTicketRowMapper();
  }
}
