/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 04 11:16:30 GMT 2018
 */

package com.polimi.travlendar.backend.database;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.mysql.jdbc.JDBC4ResultSet;
import com.mysql.jdbc.MySQLConnection;
import com.mysql.jdbc.StatementImpl;
import com.polimi.travlendar.backend.database.UrbanTicketRowMapper;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UrbanTicketRowMapper_ESTest extends UrbanTicketRowMapper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UrbanTicketRowMapper urbanTicketRowMapper0 = new UrbanTicketRowMapper();
      JDBC4ResultSet jDBC4ResultSet0 = new JDBC4ResultSet((-672L), (-672L), (MySQLConnection) null, (StatementImpl) null);
      try { 
        urbanTicketRowMapper0.mapRow(jDBC4ResultSet0, (-2252));
        fail("Expecting exception: SQLException");
      
      } catch(SQLException e) {
         //
         // Operation not allowed after ResultSet closed
         //
         assertThrownBy("com.mysql.jdbc.SQLError", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UrbanTicketRowMapper urbanTicketRowMapper0 = new UrbanTicketRowMapper();
      // Undeclared exception!
      try { 
        urbanTicketRowMapper0.mapRow((ResultSet) null, 298);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.polimi.travlendar.backend.database.UrbanTicketRowMapper", e);
      }
  }
}
