/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 04 11:35:30 GMT 2018
 */

package com.polimi.travlendar;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.polimi.travlendar.TravlendarApplication;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.TooManyResourcesException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TravlendarApplication_ESTest extends TravlendarApplication_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        TravlendarApplication.main((String[]) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Args must not be null
         //
         assertThrownBy("org.springframework.util.Assert", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[2];
      stringArray0[0] = "org.apache.commons.logging.Log";
      String string0 = "6TCDa|?e/";
      stringArray0[1] = "6TCDa|?e/";
      // Undeclared exception!
      try { 
        TravlendarApplication.main(stringArray0);
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
         assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "";
      // Undeclared exception!
      try { 
        TravlendarApplication.main(stringArray0);
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
         assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TravlendarApplication travlendarApplication0 = new TravlendarApplication();
      TravlendarApplication travlendarApplication1 = new TravlendarApplication();
      TravlendarApplication travlendarApplication2 = new TravlendarApplication();
      TravlendarApplication travlendarApplication3 = new TravlendarApplication();
      String[] stringArray0 = new String[4];
      stringArray0[0] = "";
      stringArray0[1] = "NW1dR;6h";
      stringArray0[2] = "";
      stringArray0[3] = "?!a>=4/-TP/";
      // Undeclared exception!
      try { 
        TravlendarApplication.main(stringArray0);
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
         assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TravlendarApplication travlendarApplication0 = new TravlendarApplication();
      String[] stringArray0 = new String[7];
      stringArray0[0] = "";
      String string0 = "";
      stringArray0[1] = "";
      stringArray0[2] = "o";
      String string1 = "";
      stringArray0[3] = "";
      String string2 = "Operation [newFactory] is not supported in jcl-over-slf4j. See also ";
      stringArray0[4] = "Operation [newFactory] is not supported in jcl-over-slf4j. See also ";
      String string3 = "R_I,'zZ";
      stringArray0[5] = "R_I,'zZ";
      String string4 = ")MX!AHC[RLr<&(j4FS";
      stringArray0[6] = ")MX!AHC[RLr<&(j4FS";
      // Undeclared exception!
      try { 
        TravlendarApplication.main(stringArray0);
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
         assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String[] stringArray0 = new String[7];
      stringArray0[0] = "9Xp";
      stringArray0[1] = ")/6l[$(l;+1 m";
      stringArray0[2] = "tGYH<;j1i7";
      stringArray0[3] = ")mCNIU:/oX/68q?";
      stringArray0[4] = "";
      stringArray0[5] = "";
      stringArray0[6] = "O[";
      // Undeclared exception!
      try { 
        TravlendarApplication.main(stringArray0);
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
         assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      String[] stringArray0 = new String[9];
      stringArray0[0] = "Qi'r4";
      stringArray0[1] = "_ZA$F1aQpz#C";
      stringArray0[2] = "";
      stringArray0[3] = "7)Xb!]XtX9l^d";
      stringArray0[4] = "cX`vAje1.@]";
      stringArray0[5] = ".Ag>";
      stringArray0[6] = "commons-logging.properties";
      stringArray0[7] = "";
      stringArray0[8] = "";
      // Undeclared exception!
      try { 
        TravlendarApplication.main(stringArray0);
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
         assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      TravlendarApplication travlendarApplication0 = new TravlendarApplication();
      String[] stringArray0 = new String[6];
      stringArray0[0] = "?|";
      stringArray0[1] = "I.cN;0EX\"#";
      stringArray0[2] = "";
      stringArray0[3] = "";
      stringArray0[4] = "org.apache.commons.logging.impl.SLF4JLogFactory";
      stringArray0[5] = "0D)XtNH^C,!^`";
      // Undeclared exception!
      try { 
        TravlendarApplication.main(stringArray0);
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
         assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      TravlendarApplication travlendarApplication0 = new TravlendarApplication();
      String[] stringArray0 = new String[7];
      stringArray0[0] = "Z7";
      stringArray0[1] = "null";
      stringArray0[2] = "";
      stringArray0[3] = "";
      stringArray0[4] = "priority";
      stringArray0[5] = "org.apache.commons.logging.LogFactory";
      stringArray0[6] = "vzV|S(o<WGDp";
      // Undeclared exception!
      try { 
        TravlendarApplication.main(stringArray0);
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
         assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      String[] stringArray0 = new String[5];
      stringArray0[0] = "";
      stringArray0[1] = "";
      stringArray0[2] = "";
      stringArray0[3] = "e:o!f9bmd";
      stringArray0[4] = "";
      // Undeclared exception!
      try { 
        TravlendarApplication.main(stringArray0);
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
         assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }
}
