/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 05 21:56:13 GMT 2018
 */

package com.polimi.travlendar.frontend.ui.forms;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.MockitoExtension.*;
import com.polimi.travlendar.backend.beans.UserService;
import com.polimi.travlendar.backend.model.user.User;
import com.polimi.travlendar.frontend.ui.forms.RegisterForm;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;
import org.springframework.jdbc.core.JdbcTemplate;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RegisterForm_ESTest extends RegisterForm_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RegisterForm registerForm0 = new RegisterForm();
      UserService userService0 = new UserService();
      JdbcTemplate jdbcTemplate0 = mock(JdbcTemplate.class, new ViolatedAssumptionAnswer());
      Injector.inject(userService0, (Class<?>) UserService.class, "jdbcTemplate", (Object) jdbcTemplate0);
      Injector.validateBean(userService0, (Class<?>) UserService.class);
      Injector.inject(registerForm0, (Class<?>) RegisterForm.class, "service", (Object) userService0);
      User user0 = new User();
      Injector.inject(user0, (Class<?>) User.class, "service", (Object) userService0);
      Injector.validateBean(user0, (Class<?>) User.class);
      Injector.inject(registerForm0, (Class<?>) RegisterForm.class, "user", (Object) user0);
      Injector.validateBean(registerForm0, (Class<?>) RegisterForm.class);
      registerForm0.checkConfirm();
      assertFalse(registerForm0.isAttached());
  }
}
