/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Jan 04 11:21:30 GMT 2018
 */

package com.polimi.travlendar.backend.model.events;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class Meeting_ESTest_scaffolding {

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);

  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.polimi.travlendar.backend.model.events.Meeting"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init(); 
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("java.vm.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.specification.version", "1.8"); 
            java.lang.System.setProperty("java.home", "/usr/lib/jvm/java-8-oracle/jre"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("user.home", "/home/jaycaves"); 
                                        java.lang.System.setProperty("user.dir", "/home/jaycaves/Desktop/FumagalliGrottiGullo/Implementation"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("awt.toolkit", "sun.awt.X11.XToolkit"); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("file.separator", "/"); 
        java.lang.System.setProperty("java.awt.graphicsenv", "sun.awt.X11GraphicsEnvironment"); 
    java.lang.System.setProperty("java.awt.printerjob", "sun.print.PSPrinterJob"); 
    java.lang.System.setProperty("java.class.path", "/tmp/EvoSuite_pathingJar2764208889567197362.jar"); 
    java.lang.System.setProperty("java.class.version", "52.0"); 
        java.lang.System.setProperty("java.endorsed.dirs", "/usr/lib/jvm/java-8-oracle/jre/lib/endorsed"); 
    java.lang.System.setProperty("java.ext.dirs", "/usr/lib/jvm/java-8-oracle/jre/lib/ext:/usr/java/packages/lib/ext"); 
    java.lang.System.setProperty("java.library.path", "lib"); 
    java.lang.System.setProperty("java.runtime.name", "Java(TM) SE Runtime Environment"); 
    java.lang.System.setProperty("java.runtime.version", "1.8.0_131-b11"); 
    java.lang.System.setProperty("java.specification.name", "Java Platform API Specification"); 
    java.lang.System.setProperty("java.specification.vendor", "Oracle Corporation"); 
        java.lang.System.setProperty("java.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vendor.url", "http://java.oracle.com/"); 
    java.lang.System.setProperty("java.version", "1.8.0_131"); 
    java.lang.System.setProperty("java.vm.info", "mixed mode"); 
    java.lang.System.setProperty("java.vm.name", "Java HotSpot(TM) 64-Bit Server VM"); 
    java.lang.System.setProperty("java.vm.specification.name", "Java Virtual Machine Specification"); 
    java.lang.System.setProperty("java.vm.specification.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vm.specification.version", "1.8"); 
    java.lang.System.setProperty("java.vm.version", "25.131-b11"); 
    java.lang.System.setProperty("line.separator", "\n"); 
    java.lang.System.setProperty("os.arch", "amd64"); 
    java.lang.System.setProperty("os.name", "Linux"); 
    java.lang.System.setProperty("os.version", "4.10.0-42-generic"); 
    java.lang.System.setProperty("path.separator", ":"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "jaycaves"); 
    java.lang.System.setProperty("user.timezone", "Europe/Rome"); 
          }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Meeting_ESTest_scaffolding.class.getClassLoader() ,
      "com.vaadin.event.Action$Listener",
      "com.vaadin.ui.UI",
      "com.vaadin.server.Sizeable$Unit",
      "com.vaadin.ui.HasComponents",
      "com.vaadin.shared.AbstractComponentState",
      "com.vaadin.event.ConnectorEvent",
      "com.vaadin.server.VaadinRequest",
      "com.vaadin.server.ErrorHandler",
      "com.vaadin.ui.Component$ErrorEvent",
      "com.vaadin.event.MethodEventSource",
      "elemental.json.JsonValue",
      "com.vaadin.event.Action$Handler",
      "org.jsoup.nodes.Element",
      "com.vaadin.ui.declarative.DesignContext",
      "com.vaadin.event.ContextClickEvent",
      "com.vaadin.event.ShortcutAction",
      "com.vaadin.shared.Connector",
      "com.vaadin.ui.HasComponents$ComponentAttachDetachNotifier",
      "com.vaadin.shared.MouseEventDetails",
      "com.vaadin.event.ContextClickEvent$ContextClickNotifier",
      "com.vaadin.server.VaadinResponse",
      "com.vaadin.event.Action",
      "com.vaadin.data.validator.RangeValidator",
      "com.vaadin.server.Extension",
      "com.vaadin.server.ClientConnector$AttachEvent",
      "org.jsoup.nodes.Node",
      "com.vaadin.ui.AbstractComponent",
      "com.vaadin.shared.communication.ClientRpc",
      "com.vaadin.server.ClientConnector$DetachListener",
      "com.vaadin.server.SerializableFunction",
      "com.polimi.travlendar.gmaps.PredictionCaptionGenerator",
      "org.jsoup.nodes.Attributes",
      "com.vaadin.ui.Component$Event",
      "com.vaadin.ui.Component$Listener",
      "com.polimi.travlendar.backend.model.events.Meeting$State",
      "com.vaadin.data.ValidationResult",
      "com.polimi.travlendar.gmaps.DefaultCaptionGenerator",
      "com.polimi.travlendar.backend.model.user.PreferenceLevel",
      "com.vaadin.server.ClientConnector$DetachEvent",
      "com.vaadin.shared.ui.composite.CompositeState",
      "com.vaadin.data.Validator",
      "com.vaadin.util.ReflectTools",
      "com.vaadin.event.ConnectorActionManager",
      "com.vaadin.server.AbstractClientConnector",
      "com.polimi.travlendar.backend.model.events.Meeting",
      "com.vaadin.server.Resource",
      "com.vaadin.shared.Registration",
      "com.vaadin.event.MouseEvents$ClickEvent",
      "com.vaadin.data.ValueContext",
      "com.vaadin.server.VariableOwner",
      "com.vaadin.server.ClientConnector",
      "com.vaadin.event.ActionManager",
      "com.vaadin.shared.ui.ContentMode",
      "com.vaadin.ui.ItemCaptionGenerator",
      "com.vaadin.shared.communication.SharedState",
      "com.vaadin.server.ServerRpcManager",
      "com.vaadin.shared.communication.ServerRpc",
      "com.vaadin.event.ConnectorEventListener",
      "com.vaadin.ui.AbstractSingleComponentContainer",
      "com.vaadin.ui.LegacyComponent",
      "com.vaadin.ui.Composite",
      "com.vaadin.server.ErrorMessage",
      "com.vaadin.server.Sizeable",
      "com.vaadin.ui.SingleComponentContainer",
      "com.vaadin.event.ContextClickEvent$ContextClickListener",
      "com.vaadin.server.ClientConnector$AttachListener",
      "com.vaadin.server.VaadinSession",
      "com.vaadin.data.validator.AbstractValidator",
      "com.vaadin.event.UIEvents$PollNotifier",
      "com.vaadin.ui.Component$Focusable",
      "com.vaadin.event.ShortcutListener",
      "elemental.json.JsonObject",
      "com.vaadin.event.Action$Notifier",
      "com.vaadin.event.SerializableEventListener",
      "com.vaadin.event.Action$Container",
      "com.vaadin.ui.Component"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(Meeting_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.polimi.travlendar.backend.model.events.Meeting$State",
      "com.polimi.travlendar.backend.model.user.PreferenceLevel",
      "com.vaadin.data.validator.AbstractValidator",
      "com.vaadin.data.validator.RangeValidator",
      "com.polimi.travlendar.gmaps.DefaultCaptionGenerator",
      "com.vaadin.server.AbstractClientConnector",
      "com.vaadin.util.ReflectTools",
      "com.vaadin.ui.AbstractComponent",
      "com.vaadin.ui.Composite",
      "com.vaadin.server.Sizeable$Unit",
      "com.polimi.travlendar.gmaps.PredictionCaptionGenerator"
    );
  }
}
