/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 04 11:25:04 GMT 2018
 */

package com.polimi.travlendar.backend.model.events;

import org.junit.Test;
import static org.junit.Assert.*;
import com.polimi.travlendar.backend.model.events.Meeting;
import com.polimi.travlendar.backend.model.events.OnEventClick;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class OnEventClick_ESTest extends OnEventClick_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      OnEventClick onEventClick0 = new OnEventClick((Meeting) null);
      assertFalse(onEventClick0.isAttached());
  }
}
