/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 04 11:33:46 GMT 2018
 */

package com.polimi.travlendar.frontend.ui.pages.gmaps;

import org.junit.Test;
import static org.junit.Assert.*;
import com.polimi.travlendar.frontend.ui.pages.gmaps.MapsAddOnPage;
import com.vaadin.navigator.ViewChangeListener;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MapsAddOnPage_ESTest extends MapsAddOnPage_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MapsAddOnPage mapsAddOnPage0 = new MapsAddOnPage();
      mapsAddOnPage0.enter((ViewChangeListener.ViewChangeEvent) null);
      assertFalse(mapsAddOnPage0.isAttached());
  }
}
