/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 05 21:50:17 GMT 2018
 */

package com.polimi.travlendar.frontend.ui.pages.gmaps;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.google.maps.model.PlacesSearchResult;
import com.polimi.travlendar.frontend.ui.pages.gmaps.PlaceSearchPage;
import com.polimi.travlendar.gmaps.PlaceSearchField;
import com.vaadin.navigator.ViewChangeListener;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PlaceSearchPage_ESTest extends PlaceSearchPage_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PlaceSearchPage placeSearchPage0 = new PlaceSearchPage();
      PlacesSearchResult placesSearchResult0 = new PlacesSearchResult();
      // Undeclared exception!
      try { 
        placeSearchPage0.deliverPlace((PlaceSearchField) null, placesSearchResult0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.polimi.travlendar.frontend.ui.pages.gmaps.PlaceSearchPage", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PlaceSearchPage placeSearchPage0 = new PlaceSearchPage();
      PlaceSearchField placeSearchField0 = new PlaceSearchField();
      PlacesSearchResult placesSearchResult0 = new PlacesSearchResult();
      // Undeclared exception!
      try { 
        placeSearchPage0.deliverPlace(placeSearchField0, placesSearchResult0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.polimi.travlendar.frontend.ui.pages.gmaps.PlaceSearchPage", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PlaceSearchPage placeSearchPage0 = new PlaceSearchPage();
      // Undeclared exception!
      try { 
        placeSearchPage0.resultNotFoundError();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.vaadin.ui.Notification", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PlaceSearchPage placeSearchPage0 = new PlaceSearchPage();
      placeSearchPage0.enter((ViewChangeListener.ViewChangeEvent) null);
      PlaceSearchField placeSearchField0 = new PlaceSearchField();
      // Undeclared exception!
      try { 
        placeSearchPage0.deliverPlace(placeSearchField0, (PlacesSearchResult) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.polimi.travlendar.gmaps.VaadinMap", e);
      }
  }
}
