/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 05 22:08:33 GMT 2018
 */

package com.polimi.travlendar.frontend.ui.pages;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.MockitoExtension.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.polimi.travlendar.frontend.ui.forms.LoginForm;
import com.polimi.travlendar.frontend.ui.forms.RegisterForm;
import com.polimi.travlendar.frontend.ui.pages.AuthenticationPage;
import com.vaadin.navigator.ViewChangeListener;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AuthenticationPage_ESTest extends AuthenticationPage_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AuthenticationPage authenticationPage0 = new AuthenticationPage();
      LoginForm loginForm0 = mock(LoginForm.class, new ViolatedAssumptionAnswer());
      Injector.inject(authenticationPage0, (Class<?>) AuthenticationPage.class, "loginForm", (Object) loginForm0);
      RegisterForm registerForm0 = mock(RegisterForm.class, new ViolatedAssumptionAnswer());
      Injector.inject(authenticationPage0, (Class<?>) AuthenticationPage.class, "registerForm", (Object) registerForm0);
      Injector.validateBean(authenticationPage0, (Class<?>) AuthenticationPage.class);
      ViewChangeListener.ViewChangeEvent viewChangeListener_ViewChangeEvent0 = mock(ViewChangeListener.ViewChangeEvent.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        authenticationPage0.enter(viewChangeListener_ViewChangeEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.polimi.travlendar.frontend.ui.pages.AuthenticationPage", e);
      }
  }
}
