/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Jan 05 22:17:09 GMT 2018
 */

package com.polimi.travlendar.frontend.ui.pages;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class CreateEventPage_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.polimi.travlendar.frontend.ui.pages.CreateEventPage"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.timezone", "Europe/Rome"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(CreateEventPage_ESTest_scaffolding.class.getClassLoader() ,
      "com.vaadin.ui.CustomComponent",
      "com.vaadin.ui.Alignment",
      "com.vaadin.server.Sizeable$Unit",
      "org.springframework.beans.factory.annotation.Autowired",
      "com.vaadin.ui.HasComponents",
      "com.vaadin.shared.AbstractComponentState",
      "com.vaadin.ui.Button$ClickEvent",
      "com.vaadin.ui.Component$ErrorEvent",
      "com.vaadin.server.ErrorHandler",
      "elemental.json.JsonValue",
      "com.vaadin.shared.ui.orderedlayout.FormLayoutState",
      "com.vaadin.data.HasValue",
      "org.jsoup.nodes.Element",
      "com.vaadin.event.ShortcutAction",
      "com.vaadin.event.ContextClickEvent$ContextClickNotifier",
      "org.springframework.dao.NonTransientDataAccessException",
      "com.vaadin.server.VaadinResponse",
      "com.vaadin.shared.ui.AbstractLayoutState",
      "com.vaadin.event.LayoutEvents$LayoutClickNotifier",
      "com.polimi.travlendar.frontend.ui.forms.EventForm",
      "com.vaadin.server.Extension",
      "com.vaadin.shared.ui.orderedlayout.AbstractOrderedLayoutState$ChildComponentData",
      "com.vaadin.shared.ui.LayoutClickRpc",
      "com.vaadin.server.ClientConnector$AttachEvent",
      "com.vaadin.ui.Layout$SpacingHandler",
      "com.vaadin.ui.AbstractTextField",
      "com.vaadin.data.HasFilterableDataProvider",
      "com.vaadin.navigator.ViewBeforeLeaveEvent",
      "com.vaadin.navigator.View",
      "com.vaadin.ui.Component$Event",
      "com.vaadin.ui.HasComponents$ComponentDetachListener",
      "com.vaadin.event.FieldEvents$BlurNotifier",
      "com.vaadin.spring.annotation.VaadinSessionScope",
      "com.vaadin.ui.VerticalLayout",
      "com.vaadin.event.EventRouter",
      "com.vaadin.server.ClientConnector$DetachEvent",
      "org.springframework.context.annotation.Scope",
      "com.polimi.travlendar.backend.model.user.PreferenceLevel",
      "com.vaadin.ui.AbstractDateField",
      "com.vaadin.ui.Layout$AlignmentHandler",
      "com.vaadin.event.ConnectorActionManager",
      "com.vaadin.util.ReflectTools",
      "com.vaadin.server.AbstractClientConnector",
      "com.vaadin.server.SizeWithUnit",
      "com.polimi.travlendar.backend.model.events.Meeting",
      "com.vaadin.server.Resource",
      "com.vaadin.spring.annotation.ViewScope",
      "com.polimi.travlendar.gmaps.LocationForm",
      "com.vaadin.server.VariableOwner",
      "com.vaadin.ui.AbstractOrderedLayout",
      "com.vaadin.event.ActionManager",
      "com.vaadin.ui.AbstractLocalDateField",
      "com.polimi.travlendar.frontend.ui.forms.EventForm$CreateEventRecap",
      "com.vaadin.shared.ui.ContentMode",
      "com.vaadin.shared.communication.ServerRpc",
      "com.vaadin.event.ConnectorEventListener",
      "com.vaadin.ui.AbstractSingleComponentContainer",
      "com.vaadin.server.ServerRpcManager$RpcInvocationException",
      "com.vaadin.ui.SingleComponentContainer",
      "com.vaadin.ui.HasComponents$ComponentDetachEvent",
      "com.vaadin.data.HasValue$ValueChangeEvent",
      "com.vaadin.ui.HasValueChangeMode",
      "com.vaadin.ui.AbstractSingleSelect",
      "com.vaadin.ui.Button",
      "com.vaadin.ui.Layout",
      "com.vaadin.server.ClientConnector$AttachListener",
      "com.vaadin.ui.HorizontalLayout",
      "com.vaadin.ui.FormLayout",
      "com.vaadin.event.LayoutEvents$LayoutClickListener",
      "elemental.json.JsonObject",
      "com.polimi.travlendar.gmaps.PlaceSearchFieldClient",
      "com.vaadin.event.Action$Notifier",
      "com.vaadin.ui.AbstractComponentContainer",
      "com.vaadin.event.Action$Container",
      "com.vaadin.event.FieldEvents$FocusNotifier",
      "com.vaadin.ui.Panel",
      "com.polimi.travlendar.backend.model.user.User",
      "com.vaadin.ui.TextField",
      "com.vaadin.event.Action$Listener",
      "com.vaadin.ui.UI",
      "com.vaadin.ui.Window",
      "com.vaadin.ui.ComponentContainer",
      "com.vaadin.event.ConnectorEvent",
      "com.vaadin.server.VaadinRequest",
      "com.github.appreciated.app.layout.annotations.MenuIcon",
      "com.vaadin.event.MethodEventSource",
      "com.vaadin.shared.ui.AlignmentInfo",
      "com.vaadin.event.Action$Handler",
      "com.vaadin.ui.declarative.DesignContext",
      "com.vaadin.event.ContextClickEvent",
      "com.vaadin.icons.VaadinIcons",
      "com.vaadin.ui.HasComponents$ComponentAttachEvent",
      "com.vaadin.server.FontIcon",
      "com.vaadin.shared.Connector",
      "com.vaadin.ui.HasComponents$ComponentAttachDetachNotifier",
      "com.vaadin.shared.MouseEventDetails",
      "org.springframework.dao.EmptyResultDataAccessException",
      "com.vaadin.event.Action",
      "org.springframework.core.NestedRuntimeException",
      "com.vaadin.ui.Layout$MarginHandler",
      "com.vaadin.ui.DateField",
      "com.polimi.travlendar.frontend.ui.pages.CreateEventPage",
      "com.polimi.travlendar.backend.model.events.TimeSelectorComponent",
      "com.vaadin.shared.ui.MarginInfo",
      "org.jsoup.nodes.Node",
      "com.vaadin.ui.AbstractComponent",
      "com.vaadin.ui.AbstractField",
      "com.vaadin.shared.communication.ClientRpc",
      "org.springframework.jdbc.core.RowMapper",
      "com.vaadin.shared.ui.orderedlayout.AbstractOrderedLayoutState",
      "com.vaadin.server.ClientConnector$DetachListener",
      "com.vaadin.ui.AbstractFocusable",
      "org.jsoup.nodes.Attributes",
      "org.springframework.dao.DataAccessException",
      "org.springframework.dao.IncorrectResultSizeDataAccessException",
      "com.vaadin.ui.Component$Listener",
      "com.vaadin.ui.ComboBox",
      "com.polimi.travlendar.backend.model.events.Meeting$State",
      "com.vaadin.event.HasUserOriginated",
      "org.springframework.dao.DataRetrievalFailureException",
      "com.vaadin.server.Scrollable",
      "com.vaadin.spring.annotation.SpringComponent",
      "com.polimi.travlendar.backend.beans.EventService",
      "com.vaadin.event.LayoutEvents$LayoutClickEvent",
      "com.vaadin.shared.Registration",
      "com.vaadin.shared.ui.orderedlayout.AbstractOrderedLayoutServerRpc",
      "com.vaadin.event.MouseEvents$ClickEvent",
      "com.vaadin.ui.AbstractListing",
      "com.vaadin.server.ClientConnector",
      "com.vaadin.shared.ui.AbstractComponentContainerState",
      "com.vaadin.event.Action$ShortcutNotifier",
      "com.vaadin.navigator.ViewChangeListener",
      "com.vaadin.spring.annotation.SpringView",
      "com.vaadin.ui.SingleSelect",
      "com.vaadin.shared.communication.SharedState",
      "com.vaadin.navigator.ViewChangeListener$ViewChangeEvent",
      "com.vaadin.server.ServerRpcManager",
      "org.springframework.context.annotation.ScopedProxyMode",
      "com.vaadin.ui.LegacyComponent",
      "com.vaadin.server.ErrorMessage",
      "com.vaadin.server.Sizeable",
      "com.vaadin.ui.HasComponents$ComponentAttachListener",
      "com.vaadin.event.ContextClickEvent$ContextClickListener",
      "com.vaadin.navigator.Navigator",
      "org.springframework.stereotype.Component",
      "com.vaadin.data.HasItems",
      "com.vaadin.server.VaadinSession",
      "com.polimi.travlendar.backend.model.events.Schedule",
      "com.vaadin.event.UIEvents$PollNotifier",
      "com.vaadin.event.ShortcutListener",
      "com.vaadin.ui.Component$Focusable",
      "com.vaadin.shared.ui.orderedlayout.VerticalLayoutState",
      "com.vaadin.ui.AbstractLayout",
      "com.vaadin.event.SerializableEventListener",
      "com.vaadin.ui.Component"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("com.polimi.travlendar.backend.beans.EventService", false, CreateEventPage_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.polimi.travlendar.frontend.ui.forms.EventForm", false, CreateEventPage_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.vaadin.navigator.ViewChangeListener$ViewChangeEvent", false, CreateEventPage_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(CreateEventPage_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.vaadin.server.AbstractClientConnector",
      "com.vaadin.util.ReflectTools",
      "com.vaadin.ui.AbstractComponent",
      "com.vaadin.ui.AbstractComponentContainer",
      "com.vaadin.ui.AbstractLayout",
      "com.vaadin.ui.Alignment",
      "com.vaadin.ui.AbstractOrderedLayout",
      "com.vaadin.ui.VerticalLayout",
      "com.polimi.travlendar.frontend.ui.pages.CreateEventPage",
      "com.vaadin.icons.VaadinIcons",
      "org.springframework.context.annotation.ScopedProxyMode",
      "com.vaadin.server.ServerRpcManager",
      "com.vaadin.server.SizeWithUnit",
      "com.vaadin.shared.communication.SharedState",
      "com.vaadin.shared.AbstractComponentState",
      "com.vaadin.shared.ui.AbstractComponentContainerState",
      "com.vaadin.shared.ui.AbstractLayoutState",
      "com.vaadin.shared.ui.orderedlayout.AbstractOrderedLayoutState",
      "com.vaadin.shared.ui.orderedlayout.VerticalLayoutState",
      "com.vaadin.shared.ui.MarginInfo",
      "com.vaadin.ui.FormLayout",
      "com.polimi.travlendar.frontend.ui.forms.EventForm",
      "com.vaadin.ui.HasComponents$ComponentAttachListener",
      "com.vaadin.event.EventRouter",
      "com.vaadin.event.ListenerMethod",
      "com.vaadin.navigator.ViewChangeListener$ViewChangeEvent",
      "com.vaadin.event.ConnectorEvent",
      "com.vaadin.ui.Component$Event",
      "com.vaadin.ui.HasComponents$ComponentAttachEvent",
      "com.vaadin.shared.ui.orderedlayout.AbstractOrderedLayoutState$ChildComponentData",
      "com.vaadin.shared.ui.AlignmentInfo",
      "com.vaadin.event.LayoutEvents$LayoutClickListener",
      "com.vaadin.shared.ui.ComponentStateUtil",
      "com.vaadin.server.Sizeable",
      "com.vaadin.shared.communication.URLReference",
      "com.vaadin.server.ResourceReference",
      "com.vaadin.navigator.ViewBeforeLeaveEvent",
      "org.jsoup.nodes.Node",
      "org.jsoup.nodes.Element",
      "org.jsoup.parser.Tag",
      "org.jsoup.nodes.Attributes",
      "org.jsoup.nodes.Document$OutputSettings$Syntax",
      "org.jsoup.nodes.Attribute",
      "org.jsoup.select.Elements",
      "com.vaadin.ui.Component$ErrorEvent",
      "com.vaadin.ui.HasComponents$ComponentDetachListener",
      "com.vaadin.event.Action",
      "com.vaadin.event.ShortcutAction",
      "com.vaadin.event.ShortcutListener",
      "com.vaadin.event.ActionManager",
      "com.vaadin.event.ConnectorActionManager",
      "com.vaadin.shared.MouseEventDetails$MouseButton",
      "com.vaadin.event.MouseEvents$ClickEvent",
      "com.vaadin.event.ContextClickEvent",
      "com.vaadin.server.ClientConnector$DetachEvent",
      "com.vaadin.server.AbstractExtension",
      "com.vaadin.server.Responsive",
      "com.vaadin.server.ClientConnector$AttachListener",
      "com.vaadin.server.LegacyCommunicationManager",
      "com.vaadin.server.ClientConnector$DetachListener",
      "com.vaadin.server.ComponentSizeValidator",
      "com.vaadin.server.Sizeable$Unit",
      "com.vaadin.shared.ui.ContentMode"
    );
  }
}
