/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 05 22:18:24 GMT 2018
 */

package com.polimi.travlendar.frontend.ui.pages;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.MockitoExtension.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.polimi.travlendar.backend.beans.EventService;
import com.polimi.travlendar.backend.model.events.Schedule;
import com.polimi.travlendar.backend.model.user.User;
import com.polimi.travlendar.frontend.ui.pages.SchedulePage;
import com.vaadin.navigator.ViewChangeListener;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SchedulePage_ESTest extends SchedulePage_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SchedulePage schedulePage0 = new SchedulePage();
      EventService eventService0 = mock(EventService.class, new ViolatedAssumptionAnswer());
      doReturn((List) null).when(eventService0).getMeetings(any(com.polimi.travlendar.backend.model.user.User.class));
      Injector.inject(schedulePage0, (Class<?>) SchedulePage.class, "eService", (Object) eventService0);
      Schedule schedule0 = mock(Schedule.class, new ViolatedAssumptionAnswer());
      Injector.inject(schedulePage0, (Class<?>) SchedulePage.class, "schedule", (Object) schedule0);
      User user0 = mock(User.class, new ViolatedAssumptionAnswer());
      Injector.inject(schedulePage0, (Class<?>) SchedulePage.class, "user", (Object) user0);
      Injector.validateBean(schedulePage0, (Class<?>) SchedulePage.class);
      ViewChangeListener.ViewChangeEvent viewChangeListener_ViewChangeEvent0 = mock(ViewChangeListener.ViewChangeEvent.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        schedulePage0.enter(viewChangeListener_ViewChangeEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.polimi.travlendar.frontend.ui.pages.SchedulePage", e);
      }
  }
}
