/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 05 21:19:36 GMT 2018
 */

package com.polimi.travlendar.backend.database;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.polimi.travlendar.backend.database.MeetingRowMapper;
import java.sql.ResultSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MeetingRowMapper_ESTest extends MeetingRowMapper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MeetingRowMapper meetingRowMapper0 = new MeetingRowMapper();
      // Undeclared exception!
      try { 
        meetingRowMapper0.mapRow((ResultSet) null, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.polimi.travlendar.backend.database.MeetingRowMapper", e);
      }
  }
}
