/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 05 22:17:52 GMT 2018
 */

package com.polimi.travlendar.backend.database;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.MockitoExtension.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.polimi.travlendar.backend.database.UserRowMapper;
import com.polimi.travlendar.backend.model.user.User;
import java.sql.ResultSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UserRowMapper_ESTest extends UserRowMapper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UserRowMapper userRowMapper0 = new UserRowMapper();
      // Undeclared exception!
      try { 
        userRowMapper0.mapRow((ResultSet) null, (-494));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.polimi.travlendar.backend.database.UserRowMapper", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UserRowMapper userRowMapper0 = new UserRowMapper();
      ResultSet resultSet0 = mock(ResultSet.class, new ViolatedAssumptionAnswer());
      doReturn(0L, 0L).when(resultSet0).getLong(anyString());
      doReturn((String) null, (String) null, (String) null, (String) null, (String) null).when(resultSet0).getString(anyString());
      User user0 = userRowMapper0.mapRow(resultSet0, 0);
      assertNull(user0.getLast_name());
  }
}
