/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 05 22:27:06 GMT 2018
 */

package com.polimi.travlendar;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.polimi.travlendar.TravlendarApplication;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TravlendarApplication_ESTest extends TravlendarApplication_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        TravlendarApplication.main((String[]) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Args must not be null
         //
         verifyException("org.springframework.util.Assert", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TravlendarApplication travlendarApplication0 = new TravlendarApplication();
      String[] stringArray0 = new String[8];
      stringArray0[0] = "-N)yspg0QW47";
      stringArray0[1] = "";
      stringArray0[2] = "L'-1 Yc$;u/u-n%9)";
      stringArray0[3] = "[$.Y6%9?uPr";
      stringArray0[4] = "";
      stringArray0[5] = "dlRKH0=OIDkKM[GiV";
      stringArray0[6] = "";
      stringArray0[7] = "";
      // Undeclared exception!
      TravlendarApplication.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TravlendarApplication travlendarApplication0 = new TravlendarApplication();
      String[] stringArray0 = new String[5];
      stringArray0[0] = "";
      stringArray0[1] = "";
      stringArray0[2] = "]U669@?B:Xi";
      stringArray0[3] = "-0g}:2Rq-Bo9-y&IO";
      stringArray0[4] = "$6:wbk.ghD";
      // Undeclared exception!
      TravlendarApplication.main(stringArray0);
  }
}
