/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Jan 04 11:20:26 GMT 2018
 */

package com.polimi.travlendar.frontend.ui;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class TravlendarUI_ESTest_scaffolding {

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);

  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.polimi.travlendar.frontend.ui.TravlendarUI"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init(); 
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("java.vm.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.specification.version", "1.8"); 
            java.lang.System.setProperty("java.home", "/usr/lib/jvm/java-8-oracle/jre"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("user.home", "/home/jaycaves"); 
                                        java.lang.System.setProperty("user.dir", "/home/jaycaves/Desktop/FumagalliGrottiGullo/Implementation"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("awt.toolkit", "sun.awt.X11.XToolkit"); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("file.separator", "/"); 
        java.lang.System.setProperty("java.awt.graphicsenv", "sun.awt.X11GraphicsEnvironment"); 
    java.lang.System.setProperty("java.awt.printerjob", "sun.print.PSPrinterJob"); 
    java.lang.System.setProperty("java.class.path", "/tmp/EvoSuite_pathingJar3935033453835539762.jar"); 
    java.lang.System.setProperty("java.class.version", "52.0"); 
        java.lang.System.setProperty("java.endorsed.dirs", "/usr/lib/jvm/java-8-oracle/jre/lib/endorsed"); 
    java.lang.System.setProperty("java.ext.dirs", "/usr/lib/jvm/java-8-oracle/jre/lib/ext:/usr/java/packages/lib/ext"); 
    java.lang.System.setProperty("java.library.path", "lib"); 
    java.lang.System.setProperty("java.runtime.name", "Java(TM) SE Runtime Environment"); 
    java.lang.System.setProperty("java.runtime.version", "1.8.0_131-b11"); 
    java.lang.System.setProperty("java.specification.name", "Java Platform API Specification"); 
    java.lang.System.setProperty("java.specification.vendor", "Oracle Corporation"); 
        java.lang.System.setProperty("java.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vendor.url", "http://java.oracle.com/"); 
    java.lang.System.setProperty("java.version", "1.8.0_131"); 
    java.lang.System.setProperty("java.vm.info", "mixed mode"); 
    java.lang.System.setProperty("java.vm.name", "Java HotSpot(TM) 64-Bit Server VM"); 
    java.lang.System.setProperty("java.vm.specification.name", "Java Virtual Machine Specification"); 
    java.lang.System.setProperty("java.vm.specification.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vm.specification.version", "1.8"); 
    java.lang.System.setProperty("java.vm.version", "25.131-b11"); 
    java.lang.System.setProperty("line.separator", "\n"); 
    java.lang.System.setProperty("os.arch", "amd64"); 
    java.lang.System.setProperty("os.name", "Linux"); 
    java.lang.System.setProperty("os.version", "4.10.0-42-generic"); 
    java.lang.System.setProperty("path.separator", ":"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "jaycaves"); 
    java.lang.System.setProperty("user.timezone", "Europe/Rome"); 
      }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(TravlendarUI_ESTest_scaffolding.class.getClassLoader() ,
      "com.github.appreciated.app.layout.session.AppLayoutSessionHelper",
      "elemental.json.impl.JreJsonNumber",
      "com.vaadin.ui.CustomComponent",
      "elemental.json.JsonNumber",
      "com.vaadin.event.UIEvents$PollEvent",
      "com.vaadin.server.Responsive",
      "com.github.appreciated.app.layout.builder.entities.NotificationHolder",
      "elemental.json.impl.JreJsonArray",
      "com.vaadin.shared.AbstractComponentState",
      "com.vaadin.ui.Component$ErrorEvent",
      "com.vaadin.server.AbstractExtension",
      "com.vaadin.spring.annotation.EnableVaadinNavigation",
      "com.vaadin.server.Page$PopStateListener",
      "org.jsoup.nodes.Element",
      "com.vaadin.server.Page",
      "elemental.json.impl.JreJsonNull",
      "com.vaadin.ui.UIDetachedException",
      "com.vaadin.event.ShortcutAction",
      "elemental.json.impl.JsonVisitor",
      "com.vaadin.shared.ui.ui.UIServerRpc",
      "com.vaadin.event.ContextClickEvent$ContextClickNotifier",
      "org.springframework.dao.NonTransientDataAccessException",
      "com.vaadin.server.VaadinResponse",
      "elemental.json.JsonType",
      "com.github.appreciated.app.layout.component.VerticalFlexBoxLayout",
      "com.vaadin.shared.ui.AbstractLayoutState",
      "com.vaadin.server.ComponentSizeValidator",
      "com.vaadin.shared.ui.orderedlayout.AbstractOrderedLayoutState$ChildComponentData",
      "com.github.appreciated.app.layout.builder.AppLayoutConfiguration",
      "com.vaadin.shared.ui.LayoutClickRpc",
      "com.vaadin.event.MouseEvents$ClickListener",
      "com.vaadin.server.ClientConnector$AttachEvent",
      "com.vaadin.shared.ui.ui.UIState$LocaleData",
      "com.github.appreciated.app.layout.builder.providers.left.DefaultLeftNavigationBadgeElementComponentProvider",
      "com.vaadin.ui.PushConfigurationImpl",
      "com.vaadin.shared.communication.MethodInvocation",
      "com.vaadin.ui.ReconnectDialogConfigurationImpl",
      "elemental.json.impl.JreJsonValue",
      "com.vaadin.ui.HasComponents$ComponentDetachListener",
      "com.vaadin.event.FieldEvents$BlurNotifier",
      "com.vaadin.spring.annotation.VaadinSessionScope",
      "com.vaadin.shared.ui.ui.NotificationRole",
      "com.vaadin.shared.ui.ui.UIState$PushConfigurationState",
      "com.vaadin.server.WrappedSession",
      "com.vaadin.shared.ui.ui.UIState",
      "com.vaadin.ui.TooltipConfiguration",
      "org.springframework.context.annotation.Scope",
      "com.vaadin.server.DragAndDropService",
      "com.vaadin.ui.Layout$AlignmentHandler",
      "com.vaadin.event.ConnectorActionManager",
      "com.vaadin.server.AbstractClientConnector",
      "com.vaadin.server.VaadinServlet",
      "com.vaadin.ui.Image",
      "com.vaadin.server.StreamVariable",
      "com.vaadin.shared.communication.URLReference",
      "com.vaadin.server.VariableOwner",
      "com.github.appreciated.app.layout.behaviour.left.LeftResponsiveOverlay",
      "com.vaadin.server.JsonCodec$BeanProperty",
      "com.github.appreciated.app.layout.behaviour.listener.AppLayoutResizeListener$AppLayoutResizedListener",
      "com.vaadin.ui.TooltipConfigurationImpl",
      "com.vaadin.shared.ui.AbstractEmbeddedState",
      "com.vaadin.spring.navigator.SpringNavigator",
      "com.vaadin.shared.ui.image.ImageState",
      "com.vaadin.shared.communication.ServerRpc",
      "com.vaadin.ui.AbstractSingleComponentContainer",
      "com.vaadin.ui.LoadingIndicatorConfiguration",
      "elemental.json.impl.JsonContext",
      "com.vaadin.server.ServerRpcManager$RpcInvocationException",
      "com.github.appreciated.app.layout.builder.entities.DefaultNotificationHolder",
      "com.github.appreciated.app.layout.behaviour.left.LeftResponsiveHybridNoAppBar",
      "elemental.json.JsonNull",
      "com.vaadin.shared.JavaScriptConnectorState",
      "com.vaadin.server.ClientMethodInvocation",
      "com.vaadin.ui.HorizontalLayout",
      "com.vaadin.event.LayoutEvents$LayoutClickListener",
      "com.github.appreciated.app.layout.builder.entities.DefaultBadgeHolder",
      "com.vaadin.event.Action$Notifier",
      "com.github.appreciated.app.layout.component.HorizontalFlexBoxLayout",
      "com.vaadin.event.Action$Container",
      "com.vaadin.event.FieldEvents$FocusNotifier",
      "com.polimi.travlendar.backend.model.user.User",
      "com.github.appreciated.app.layout.builder.AppLayoutBuilder",
      "com.github.appreciated.app.layout.behaviour.Behaviour",
      "com.vaadin.event.Action$Listener",
      "com.vaadin.ui.UI",
      "com.vaadin.ui.Window",
      "com.github.appreciated.app.layout.behaviour.left.LeftResponsiveOverlayNoAppBar",
      "elemental.json.JsonFactory",
      "com.vaadin.event.ConnectorEvent",
      "com.vaadin.ui.ComponentContainer",
      "com.vaadin.server.VaadinRequest",
      "com.vaadin.shared.ui.ui.UIState$NotificationTypeConfiguration",
      "com.github.appreciated.app.layout.behaviour.listener.AppLayoutResizeListener",
      "com.vaadin.event.MethodEventSource",
      "com.vaadin.server.JavaScriptCallbackHelper$1",
      "com.github.appreciated.app.layout.component.RoundImage",
      "com.vaadin.server.JsonCodec$1",
      "com.vaadin.shared.ui.ui.UIState$ReconnectDialogConfigurationState",
      "com.vaadin.shared.ui.AlignmentInfo",
      "com.vaadin.server.JsonCodec$2",
      "com.vaadin.event.Action$Handler",
      "com.github.appreciated.app.layout.builder.PairComponentProvider",
      "com.vaadin.shared.ui.ui.Transport",
      "com.github.appreciated.app.layout.builder.elements.SubmenuNavigationElement",
      "com.vaadin.server.AbstractClientConnector$RpcInvocationHandler",
      "com.vaadin.icons.VaadinIcons",
      "com.vaadin.shared.MouseEventDetails$MouseButton",
      "com.vaadin.ui.HasComponents$ComponentAttachEvent",
      "com.vaadin.server.FontIcon",
      "com.vaadin.ui.GridLayout",
      "com.vaadin.ui.HasComponents$ComponentAttachDetachNotifier",
      "com.vaadin.shared.MouseEventDetails",
      "org.springframework.dao.EmptyResultDataAccessException",
      "org.springframework.core.NestedRuntimeException",
      "com.polimi.travlendar.frontend.ui.TravlendarUI$SpringConfiguration",
      "com.vaadin.server.communication.PushConnection",
      "com.vaadin.ui.Layout$MarginHandler",
      "com.vaadin.ui.UI$WindowOrderUpdateEvent",
      "com.vaadin.ui.ConnectorTracker",
      "com.vaadin.server.Page$UriFragmentChangedListener",
      "com.github.appreciated.app.layout.behaviour.left.AbstractLeftAppLayout",
      "com.github.appreciated.app.layout.builder.providers.left.DefaultLeftSubmenuNavigationElementProvider",
      "com.vaadin.ui.AbstractJavaScriptComponent",
      "com.vaadin.server.Page$UriFragmentChangedEvent",
      "com.vaadin.shared.ui.MarginInfo",
      "org.jsoup.nodes.Node",
      "com.vaadin.shared.ui.WindowOrderRpc",
      "com.github.appreciated.app.layout.builder.providers.left.DefaultLeftClickableNavigationElementProvider",
      "com.vaadin.ui.NotificationConfigurationImpl",
      "com.vaadin.server.JsonCodec$MethodProperty",
      "com.vaadin.ui.TabSheet",
      "com.vaadin.server.BootstrapResponse",
      "com.vaadin.shared.ui.customlayout.CustomLayoutState",
      "com.vaadin.shared.ui.orderedlayout.AbstractOrderedLayoutState",
      "com.polimi.travlendar.frontend.ui.TravlendarUI",
      "org.jsoup.nodes.Attributes",
      "com.vaadin.ui.JavaScriptFunction",
      "com.vaadin.event.ActionManager$ActionKeyMapper",
      "com.vaadin.server.Page$Styles",
      "com.vaadin.shared.ui.image.ImageServerRpc",
      "com.vaadin.shared.ui.ui.DebugWindowServerRpc",
      "com.vaadin.spring.annotation.SpringUI",
      "com.vaadin.ui.CssLayout",
      "com.github.appreciated.app.layout.behaviour.left.LeftOverlay",
      "com.vaadin.server.Scrollable",
      "com.vaadin.ui.AbstractSplitPanel",
      "com.vaadin.server.LocaleService",
      "com.vaadin.ui.Notification$Type",
      "com.vaadin.shared.Registration",
      "com.vaadin.shared.ui.JavaScriptComponentState",
      "com.vaadin.event.ListenerMethod",
      "com.vaadin.ui.Label",
      "com.vaadin.ui.ReconnectDialogConfiguration",
      "com.vaadin.shared.ui.ui.UIState$TooltipConfigurationState",
      "com.vaadin.shared.ui.AbstractComponentContainerState",
      "com.vaadin.ui.PushConfiguration",
      "com.github.appreciated.app.layout.behaviour.left.LeftResponsiveSmallNoAppBar",
      "elemental.json.JsonBoolean",
      "com.vaadin.ui.declarative.DesignException",
      "com.vaadin.server.PaintException",
      "com.vaadin.server.LegacyCommunicationManager$ClientCache",
      "com.vaadin.server.ServerRpcManager",
      "com.vaadin.server.ErrorEvent",
      "com.github.appreciated.app.layout.behaviour.listener.AppLayoutResizeListenerState",
      "org.springframework.context.annotation.ScopedProxyMode",
      "com.vaadin.server.ErrorMessage",
      "com.vaadin.server.Sizeable",
      "com.vaadin.shared.ui.label.LabelState",
      "com.github.appreciated.app.layout.builder.Provider",
      "com.vaadin.event.ContextClickEvent$ContextClickListener",
      "com.vaadin.server.BootstrapPageResponse",
      "com.polimi.travlendar.backend.model.events.Schedule",
      "com.vaadin.event.UIEvents$PollNotifier",
      "com.vaadin.ui.Component$Focusable",
      "com.vaadin.event.ShortcutListener",
      "com.vaadin.shared.ui.orderedlayout.VerticalLayoutState",
      "com.vaadin.ui.AbstractLayout",
      "elemental.json.impl.JreJsonString",
      "com.vaadin.server.ThemeResource",
      "com.vaadin.ui.JavaScript",
      "com.vaadin.server.UIProvider",
      "com.vaadin.server.ServerRpcMethodInvocation",
      "com.vaadin.ui.Dependency",
      "com.vaadin.ui.Alignment",
      "com.vaadin.server.Sizeable$Unit",
      "elemental.json.JsonArray",
      "com.vaadin.ui.HasComponents",
      "com.vaadin.data.provider.DataKeyMapper",
      "com.github.appreciated.app.layout.builder.entities.NotificationHolder$Notification",
      "com.github.appreciated.app.layout.builder.AppLayoutConfiguration$NavigationElementInfoProducer",
      "com.vaadin.server.ErrorHandler",
      "com.vaadin.server.JavaScriptCallbackHelper",
      "com.github.appreciated.app.layout.builder.providers.top.DefaultTopNavigationBadgeElementComponentProvider",
      "elemental.json.JsonValue",
      "elemental.json.impl.JreJsonFactory",
      "com.vaadin.spring.annotation.EnableVaadin",
      "com.vaadin.spring.annotation.UIScope",
      "com.vaadin.server.Page$BrowserWindowResizeListener",
      "com.github.appreciated.app.layout.builder.AppLayoutConfiguration$1",
      "com.vaadin.shared.extension.responsive.ResponsiveState",
      "com.github.appreciated.app.layout.builder.elements.NavigatorNavigationElement",
      "com.vaadin.shared.ui.ui.UIState$LocaleServiceState",
      "com.vaadin.ui.LoadingIndicatorConfigurationImpl",
      "com.vaadin.annotations.VaadinServletConfiguration",
      "com.github.appreciated.app.layout.builder.providers.left.DefaultLeftSectionElementComponentProvider",
      "com.vaadin.event.LayoutEvents$LayoutClickNotifier",
      "com.vaadin.server.Extension",
      "com.vaadin.server.VaadinServletService",
      "com.vaadin.shared.ui.panel.PanelState",
      "com.github.appreciated.app.layout.builder.design.AppBarDesign",
      "com.vaadin.ui.Layout$SpacingHandler",
      "com.vaadin.server.EncodeResult",
      "org.jsoup.select.Elements",
      "com.vaadin.ui.UI$3",
      "com.vaadin.ui.UI$2",
      "com.github.appreciated.app.layout.behaviour.top.AbstractTopAppLayout",
      "com.vaadin.ui.UI$1",
      "com.vaadin.server.VaadinServlet$RequestType",
      "com.vaadin.shared.ui.ComponentStateUtil",
      "com.vaadin.ui.Component$Event",
      "elemental.json.impl.JreJsonBoolean",
      "com.vaadin.ui.VerticalLayout",
      "com.github.appreciated.app.layout.behaviour.top.Top",
      "com.vaadin.event.EventRouter",
      "com.vaadin.server.ClientConnector$DetachEvent",
      "com.github.appreciated.app.layout.behaviour.left.LeftResponsiveHybrid",
      "com.vaadin.util.ReflectTools",
      "com.vaadin.server.Constants",
      "com.vaadin.server.SizeWithUnit",
      "com.github.appreciated.app.layout.builder.providers.DefaultNotificationComponentProvider",
      "elemental.json.impl.JreJsonObject",
      "com.vaadin.server.Resource",
      "com.vaadin.shared.ui.AbstractSingleComponentContainerState",
      "com.vaadin.event.MouseEvents",
      "com.vaadin.spring.annotation.SpringViewDisplay",
      "elemental.json.impl.JsonObjectContext",
      "com.vaadin.event.ActionManager",
      "com.vaadin.ui.AbstractOrderedLayout",
      "com.vaadin.server.Page$BrowserWindowResizeEvent",
      "elemental.json.JsonException",
      "com.vaadin.server.GlobalResourceHandler",
      "com.vaadin.shared.communication.PushMode",
      "com.vaadin.shared.ui.ContentMode",
      "com.polimi.travlendar.backend.beans.UserService",
      "com.github.appreciated.app.layout.builder.NavigationElementComponent",
      "com.github.appreciated.app.layout.builder.AppLayoutConfiguration$NavigatorProducer",
      "com.vaadin.event.ConnectorEventListener",
      "com.github.appreciated.app.layout.builder.providers.top.DefaultTopSectionElementComponentProvider",
      "org.springframework.context.annotation.Import",
      "com.vaadin.ui.SingleComponentContainer",
      "com.vaadin.ui.HasComponents$ComponentDetachEvent",
      "com.vaadin.ui.Layout",
      "com.vaadin.server.ClientConnector$AttachListener",
      "com.github.appreciated.app.layout.behaviour.AppLayout",
      "com.vaadin.server.communication.DateSerializer",
      "com.github.appreciated.app.layout.builder.elements.ClickableNavigationElement",
      "elemental.json.JsonObject",
      "com.vaadin.ui.AbstractComponentContainer",
      "com.vaadin.shared.ui.ui.UIState$LoadingIndicatorConfigurationState",
      "com.github.appreciated.app.layout.builder.providers.top.DefaultTopClickableNavigationElementProvider",
      "com.github.appreciated.app.layout.builder.providers.AbstractNavigationElementComponentProvider",
      "com.vaadin.ui.Panel",
      "com.vaadin.event.UIEvents$PollListener",
      "com.vaadin.server.JsonCodec",
      "com.github.appreciated.app.layout.behaviour.left.LeftHybrid",
      "com.vaadin.server.RequestHandler",
      "elemental.json.Json",
      "com.vaadin.shared.ui.ClickRpc",
      "com.vaadin.shared.ui.csslayout.CssLayoutServerRpc",
      "com.vaadin.ui.NotificationConfiguration",
      "com.vaadin.ui.declarative.DesignContext",
      "com.vaadin.event.ContextClickEvent",
      "com.vaadin.event.MouseEvents$DoubleClickEvent",
      "com.github.appreciated.app.layout.behaviour.left.LeftResponsive",
      "com.vaadin.shared.Connector",
      "com.github.appreciated.app.layout.builder.elements.AbstractNavigationElement",
      "com.github.appreciated.app.layout.builder.providers.top.DefaultTopSubmenuNavigationElementProvider",
      "com.vaadin.shared.ui.orderedlayout.HorizontalLayoutState",
      "com.github.appreciated.app.layout.behaviour.top.TopLarge",
      "com.github.appreciated.app.layout.builder.ComponentProvider",
      "com.vaadin.server.JsonCodec$FieldProperty",
      "com.vaadin.event.Action",
      "com.github.appreciated.app.layout.behaviour.left.LeftResponsiveSmall",
      "com.vaadin.server.PaintTarget",
      "com.github.appreciated.app.layout.builder.AppLayoutBuilder$Position",
      "com.vaadin.util.CurrentInstance",
      "com.vaadin.server.BootstrapFragmentResponse",
      "org.springframework.context.annotation.Configuration",
      "com.vaadin.annotations.Theme",
      "com.vaadin.ui.AbstractComponent",
      "com.vaadin.server.BootstrapListener",
      "com.vaadin.event.ListenerMethod$MethodException",
      "com.vaadin.shared.communication.ClientRpc",
      "com.vaadin.server.VaadinServlet$ScssCacheEntry",
      "org.springframework.jdbc.core.RowMapper",
      "com.vaadin.shared.ui.ui.PageState",
      "com.github.appreciated.app.layout.builder.elements.CustomNavigationElement",
      "com.vaadin.shared.ui.panel.PanelServerRpc",
      "com.vaadin.server.ClientConnector$DetachListener",
      "com.vaadin.ui.UI$WindowOrderUpdateListener",
      "org.springframework.dao.DataAccessException",
      "org.springframework.dao.IncorrectResultSizeDataAccessException",
      "com.vaadin.server.VaadinService",
      "com.vaadin.server.VaadinSession$State",
      "com.vaadin.annotations.Viewport",
      "com.vaadin.server.LegacyCommunicationManager",
      "com.vaadin.server.DeploymentConfiguration",
      "com.vaadin.ui.Component$Listener",
      "elemental.json.JsonString",
      "com.vaadin.server.ServiceException",
      "com.vaadin.ui.CustomLayout",
      "org.springframework.dao.DataRetrievalFailureException",
      "com.vaadin.server.WebBrowser",
      "com.vaadin.spring.annotation.SpringComponent",
      "com.github.appreciated.app.layout.behaviour.left.Left",
      "com.github.appreciated.app.layout.behaviour.left.LeftResponsiveHybridOverlayNoAppBar",
      "com.vaadin.event.MouseEvents$DoubleClickListener",
      "com.github.appreciated.app.layout.component.NavigationBadgeButton",
      "com.vaadin.event.LayoutEvents$LayoutClickEvent",
      "com.vaadin.ui.JavaScript$JavaScriptCallbackRpc",
      "com.vaadin.ui.Notification",
      "com.vaadin.server.ClientConnector$ConnectorErrorEvent",
      "com.vaadin.shared.ui.orderedlayout.AbstractOrderedLayoutServerRpc",
      "com.vaadin.event.MouseEvents$ClickEvent",
      "com.vaadin.shared.communication.UidlValue",
      "com.vaadin.server.ClientConnector",
      "com.vaadin.server.KeyMapper",
      "elemental.json.impl.JsonArrayContext",
      "com.vaadin.server.communication.JSONSerializer",
      "com.github.appreciated.app.layout.component.AbstractFlexBoxLayout",
      "com.vaadin.shared.communication.SharedState",
      "com.vaadin.ui.dnd.DragSourceExtension",
      "com.github.appreciated.app.layout.builder.providers.DefaultSpringNavigationElementInfoProvider",
      "com.vaadin.ui.LegacyComponent",
      "com.vaadin.server.VaadinServletRequest",
      "com.vaadin.ui.AbstractEmbedded",
      "com.vaadin.ui.HasComponents$ComponentAttachListener",
      "com.vaadin.server.VaadinServletResponse",
      "com.vaadin.shared.ui.BorderStyle",
      "com.vaadin.server.ComponentSizeValidator$InvalidLayout",
      "com.vaadin.navigator.Navigator",
      "org.springframework.stereotype.Component",
      "com.polimi.travlendar.frontend.ui.TravlendarUI$Servlet",
      "com.vaadin.server.VaadinSession",
      "com.vaadin.shared.ui.csslayout.CssLayoutState",
      "com.github.appreciated.app.layout.component.MenuHeader",
      "com.vaadin.server.ResourceReference",
      "com.vaadin.ui.SelectiveRenderer",
      "com.vaadin.event.SerializableEventListener",
      "com.vaadin.server.Page$PopStateEvent",
      "com.vaadin.ui.Component"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(TravlendarUI_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.vaadin.icons.VaadinIcons",
      "org.springframework.context.annotation.ScopedProxyMode",
      "com.vaadin.server.AbstractClientConnector",
      "com.vaadin.util.ReflectTools",
      "com.vaadin.ui.AbstractComponent",
      "com.vaadin.ui.AbstractSingleComponentContainer",
      "com.vaadin.ui.UI",
      "com.polimi.travlendar.frontend.ui.TravlendarUI",
      "com.vaadin.shared.communication.PushMode",
      "com.vaadin.server.Constants",
      "com.github.appreciated.app.layout.builder.AppLayoutBuilder$Position",
      "com.github.appreciated.app.layout.builder.design.AppBarDesign",
      "com.github.appreciated.app.layout.behaviour.Behaviour",
      "com.vaadin.util.CurrentInstance",
      "com.vaadin.server.Sizeable$Unit",
      "com.vaadin.shared.ui.ContentMode",
      "com.vaadin.server.VaadinServlet",
      "com.polimi.travlendar.frontend.ui.TravlendarUI$Servlet",
      "com.vaadin.ui.ConnectorTracker",
      "com.vaadin.shared.ui.BorderStyle",
      "com.vaadin.server.Page",
      "com.vaadin.shared.communication.SharedState",
      "com.vaadin.shared.AbstractComponentState",
      "com.vaadin.shared.ui.AbstractSingleComponentContainerState",
      "com.vaadin.shared.ui.ui.UIState",
      "com.vaadin.shared.ui.ui.UIState$TooltipConfigurationState",
      "com.vaadin.shared.ui.ui.UIState$LoadingIndicatorConfigurationState",
      "com.vaadin.shared.ui.ui.UIState$NotificationTypeConfiguration",
      "com.vaadin.shared.ui.ui.NotificationRole",
      "com.vaadin.shared.ui.ui.PageState",
      "com.vaadin.shared.ui.ui.UIState$LocaleServiceState",
      "com.vaadin.shared.ui.ui.UIState$PushConfigurationState",
      "com.vaadin.shared.ui.ui.Transport",
      "com.vaadin.shared.ui.ui.UIState$ReconnectDialogConfigurationState",
      "com.vaadin.ui.LoadingIndicatorConfigurationImpl",
      "com.vaadin.ui.UI$1",
      "com.vaadin.ui.UI$2",
      "com.vaadin.ui.UI$3",
      "com.vaadin.ui.TooltipConfigurationImpl",
      "com.vaadin.ui.PushConfigurationImpl",
      "com.vaadin.ui.ReconnectDialogConfigurationImpl",
      "com.vaadin.ui.NotificationConfigurationImpl",
      "com.vaadin.server.LocaleService",
      "com.vaadin.server.ServerRpcManager",
      "com.vaadin.shared.ui.ComponentStateUtil",
      "com.vaadin.ui.AbstractComponentContainer",
      "com.vaadin.ui.AbstractLayout",
      "com.vaadin.ui.Alignment",
      "com.vaadin.ui.AbstractOrderedLayout",
      "com.vaadin.ui.VerticalLayout",
      "com.vaadin.server.SizeWithUnit",
      "com.vaadin.shared.ui.AbstractComponentContainerState",
      "com.vaadin.shared.ui.AbstractLayoutState",
      "com.vaadin.shared.ui.orderedlayout.AbstractOrderedLayoutState",
      "com.vaadin.shared.ui.orderedlayout.VerticalLayoutState",
      "com.vaadin.shared.ui.MarginInfo",
      "com.vaadin.server.VaadinSession",
      "com.vaadin.ui.CustomLayout",
      "com.github.appreciated.app.layout.behaviour.top.AbstractTopAppLayout",
      "com.github.appreciated.app.layout.behaviour.top.Top",
      "com.vaadin.shared.ui.customlayout.CustomLayoutState",
      "com.vaadin.ui.Panel",
      "com.vaadin.shared.ui.panel.PanelState",
      "com.vaadin.ui.CssLayout",
      "com.github.appreciated.app.layout.component.AbstractFlexBoxLayout",
      "com.github.appreciated.app.layout.component.VerticalFlexBoxLayout",
      "com.vaadin.shared.ui.csslayout.CssLayoutState",
      "com.vaadin.event.ConnectorEvent",
      "com.vaadin.ui.Component$Event",
      "com.vaadin.ui.HasComponents$ComponentAttachEvent",
      "com.github.appreciated.app.layout.component.HorizontalFlexBoxLayout",
      "com.vaadin.ui.HorizontalLayout",
      "com.vaadin.shared.ui.orderedlayout.HorizontalLayoutState",
      "com.vaadin.ui.Label",
      "com.vaadin.shared.ui.label.LabelState",
      "com.vaadin.shared.ui.orderedlayout.AbstractOrderedLayoutState$ChildComponentData",
      "com.vaadin.shared.ui.AlignmentInfo",
      "com.vaadin.server.ComponentSizeValidator",
      "com.vaadin.ui.AbstractJavaScriptComponent",
      "com.github.appreciated.app.layout.behaviour.listener.AppLayoutResizeListener",
      "com.vaadin.server.JavaScriptCallbackHelper",
      "com.vaadin.shared.ui.JavaScriptComponentState",
      "com.github.appreciated.app.layout.behaviour.listener.AppLayoutResizeListenerState",
      "com.vaadin.server.JavaScriptCallbackHelper$1",
      "com.github.appreciated.app.layout.component.MenuHeader",
      "com.vaadin.server.ThemeResource",
      "com.vaadin.ui.AbstractEmbedded",
      "com.vaadin.ui.Image",
      "com.github.appreciated.app.layout.component.RoundImage",
      "com.vaadin.shared.ui.AbstractEmbeddedState",
      "com.vaadin.shared.ui.image.ImageState",
      "com.vaadin.shared.communication.URLReference",
      "com.vaadin.server.ResourceReference",
      "com.github.appreciated.app.layout.builder.AppLayoutConfiguration$1",
      "com.github.appreciated.app.layout.session.AppLayoutSessionHelper",
      "com.vaadin.server.Sizeable",
      "com.vaadin.event.UIEvents$PollListener",
      "com.vaadin.event.EventRouter",
      "com.vaadin.ui.Component$ErrorEvent",
      "com.vaadin.ui.UI$WindowOrderUpdateListener",
      "com.vaadin.ui.UIDetachedException",
      "com.github.appreciated.app.layout.behaviour.left.AbstractLeftAppLayout",
      "com.github.appreciated.app.layout.behaviour.left.LeftResponsive",
      "com.vaadin.ui.HasComponents$ComponentDetachListener",
      "com.vaadin.server.ClientConnector$DetachEvent",
      "com.vaadin.server.ClientConnector$AttachListener",
      "com.vaadin.ui.HasComponents$ComponentAttachListener",
      "com.vaadin.event.ActionManager",
      "com.vaadin.shared.MouseEventDetails$MouseButton",
      "com.vaadin.event.MouseEvents$ClickEvent",
      "com.vaadin.event.ContextClickEvent",
      "com.vaadin.server.AbstractClientConnector$RpcInvocationHandler",
      "com.vaadin.server.ClientMethodInvocation",
      "com.vaadin.event.MouseEvents$ClickListener",
      "com.vaadin.server.AbstractExtension",
      "com.vaadin.server.Responsive",
      "com.vaadin.server.ClientConnector$DetachListener",
      "com.vaadin.server.LegacyCommunicationManager",
      "com.vaadin.server.EncodeResult",
      "elemental.json.impl.JreJsonFactory",
      "elemental.json.impl.JreJsonValue",
      "elemental.json.impl.JreJsonNull",
      "elemental.json.impl.JreJsonArray",
      "com.vaadin.server.JsonCodec$1",
      "com.vaadin.server.JsonCodec",
      "elemental.json.impl.JreJsonObject",
      "com.vaadin.server.JsonCodec$MethodProperty",
      "com.vaadin.server.JsonCodec$FieldProperty",
      "elemental.json.impl.JreJsonBoolean",
      "elemental.json.impl.JreJsonString",
      "elemental.json.impl.JreJsonNumber",
      "elemental.json.JsonType",
      "com.vaadin.server.JsonCodec$2",
      "com.vaadin.event.ListenerMethod"
    );
  }
}
