/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 05 22:12:18 GMT 2018
 */

package com.polimi.fakePTS.tickets;

import org.junit.Test;
import static org.junit.Assert.*;
import com.polimi.fakePTS.tickets.TicketType;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TicketType_ESTest extends TicketType_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TicketType[] ticketTypeArray0 = TicketType.values();
      assertNotNull(ticketTypeArray0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TicketType ticketType0 = TicketType.valueOf("ONEMONTHPASS");
      assertEquals("onemonthpass", ticketType0.toString());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      List<String> list0 = TicketType.getValues();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TicketType ticketType0 = TicketType.WEEKPASS;
      String string0 = ticketType0.toString();
      assertEquals("weekpass", string0);
  }
}
