/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Jan 05 22:13:29 GMT 2018
 */

package com.polimi.travlendar.gmaps;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class JavaScriptMap_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.polimi.travlendar.gmaps.JavaScriptMap"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.timezone", "Europe/Rome"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(JavaScriptMap_ESTest_scaffolding.class.getClassLoader() ,
      "elemental.json.impl.JreJsonNumber",
      "com.vaadin.server.JsonCodec",
      "elemental.json.JsonNumber",
      "com.vaadin.event.Action$Listener",
      "elemental.json.impl.JreJsonArray",
      "elemental.json.Json",
      "com.vaadin.ui.UI",
      "com.vaadin.server.Sizeable$Unit",
      "elemental.json.JsonArray",
      "com.polimi.travlendar.gmaps.JavaScriptMap",
      "com.vaadin.shared.AbstractComponentState",
      "elemental.json.JsonFactory",
      "com.vaadin.ui.HasComponents",
      "com.vaadin.event.ConnectorEvent",
      "com.vaadin.server.VaadinRequest",
      "com.vaadin.ui.Component$ErrorEvent",
      "com.vaadin.server.ErrorHandler",
      "com.vaadin.server.JavaScriptCallbackHelper",
      "com.vaadin.event.MethodEventSource",
      "elemental.json.JsonValue",
      "elemental.json.impl.JreJsonFactory",
      "com.vaadin.server.JsonCodec$1",
      "com.vaadin.event.Action$Handler",
      "elemental.json.impl.JreJsonNull",
      "org.jsoup.nodes.Element",
      "com.vaadin.ui.declarative.DesignContext",
      "com.vaadin.event.ContextClickEvent",
      "com.vaadin.event.ShortcutAction",
      "com.vaadin.shared.Connector",
      "com.vaadin.ui.HasComponents$ComponentAttachDetachNotifier",
      "com.vaadin.annotations.JavaScript",
      "com.vaadin.event.ContextClickEvent$ContextClickNotifier",
      "com.vaadin.event.Action",
      "com.vaadin.server.VaadinResponse",
      "com.vaadin.ui.AbstractJavaScriptComponent",
      "com.vaadin.server.Extension",
      "com.vaadin.server.ClientConnector$AttachEvent",
      "org.jsoup.nodes.Node",
      "com.vaadin.server.EncodeResult",
      "com.vaadin.ui.AbstractComponent",
      "com.vaadin.server.ClientConnector$DetachListener",
      "elemental.json.impl.JreJsonValue",
      "com.vaadin.ui.Component$Event",
      "com.vaadin.ui.Component$Listener",
      "elemental.json.JsonString",
      "com.vaadin.server.ClientConnector$DetachEvent",
      "com.vaadin.event.ConnectorActionManager",
      "com.vaadin.util.ReflectTools",
      "com.vaadin.server.AbstractClientConnector",
      "com.vaadin.ui.JavaScript$JavaScriptCallbackRpc",
      "com.vaadin.server.Resource",
      "com.vaadin.shared.ui.JavaScriptComponentState",
      "com.vaadin.shared.Registration",
      "com.vaadin.event.MouseEvents$ClickEvent",
      "com.vaadin.server.VariableOwner",
      "com.vaadin.server.ClientConnector",
      "com.vaadin.event.ActionManager",
      "elemental.json.impl.JsonArrayContext",
      "elemental.json.JsonBoolean",
      "com.vaadin.server.communication.JSONSerializer",
      "elemental.json.JsonException",
      "com.vaadin.shared.ui.ContentMode",
      "com.vaadin.shared.communication.SharedState",
      "com.vaadin.shared.communication.ServerRpc",
      "com.vaadin.server.ServerRpcManager",
      "com.vaadin.event.ConnectorEventListener",
      "elemental.json.impl.JsonContext",
      "com.vaadin.ui.AbstractSingleComponentContainer",
      "com.vaadin.ui.LegacyComponent",
      "com.vaadin.server.ErrorMessage",
      "com.vaadin.server.Sizeable",
      "elemental.json.JsonNull",
      "com.vaadin.ui.SingleComponentContainer",
      "com.vaadin.event.ContextClickEvent$ContextClickListener",
      "com.vaadin.shared.JavaScriptConnectorState",
      "com.vaadin.server.communication.DateSerializer",
      "com.vaadin.server.ClientMethodInvocation",
      "com.vaadin.server.ClientConnector$AttachListener",
      "com.vaadin.event.UIEvents$PollNotifier",
      "com.vaadin.event.ShortcutListener",
      "com.vaadin.ui.Component$Focusable",
      "elemental.json.JsonObject",
      "com.vaadin.event.Action$Notifier",
      "com.vaadin.annotations.StyleSheet",
      "com.vaadin.event.Action$Container",
      "com.vaadin.event.SerializableEventListener",
      "com.vaadin.ui.Component"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(JavaScriptMap_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.vaadin.server.AbstractClientConnector",
      "com.vaadin.util.ReflectTools",
      "com.vaadin.ui.AbstractComponent",
      "com.vaadin.ui.AbstractJavaScriptComponent",
      "com.polimi.travlendar.gmaps.JavaScriptMap",
      "com.vaadin.server.JavaScriptCallbackHelper",
      "com.vaadin.server.EncodeResult",
      "elemental.json.impl.JreJsonFactory",
      "elemental.json.impl.JreJsonValue",
      "elemental.json.impl.JreJsonNull",
      "elemental.json.impl.JreJsonArray",
      "com.vaadin.server.JsonCodec$1",
      "com.vaadin.server.JsonCodec",
      "elemental.json.impl.JreJsonNumber",
      "com.vaadin.server.ClientMethodInvocation",
      "com.vaadin.shared.communication.SharedState",
      "com.vaadin.shared.AbstractComponentState",
      "com.vaadin.shared.ui.JavaScriptComponentState",
      "com.vaadin.server.ClientConnector$AttachListener",
      "com.vaadin.event.EventRouter",
      "com.vaadin.event.ListenerMethod",
      "com.vaadin.shared.ui.ComponentStateUtil",
      "com.vaadin.shared.communication.URLReference",
      "com.vaadin.server.ResourceReference",
      "com.vaadin.server.SizeWithUnit",
      "org.jsoup.nodes.Node",
      "org.jsoup.nodes.Element",
      "org.jsoup.parser.Tag",
      "org.jsoup.nodes.Attributes",
      "org.jsoup.nodes.Entities",
      "org.jsoup.nodes.Entities$EscapeMode",
      "org.jsoup.nodes.Document$OutputSettings$Syntax",
      "org.jsoup.nodes.TextNode",
      "com.vaadin.ui.declarative.DesignFormatter",
      "com.vaadin.ui.declarative.converters.DesignObjectConverter",
      "com.vaadin.ui.declarative.converters.DesignToStringConverter",
      "com.vaadin.ui.declarative.DesignFormatter$1",
      "com.vaadin.data.converter.AbstractStringToNumberConverter",
      "com.vaadin.data.converter.StringToFloatConverter",
      "com.vaadin.ui.declarative.DesignFormatter$2",
      "com.vaadin.data.converter.StringToDoubleConverter",
      "com.vaadin.ui.declarative.DesignFormatter$3",
      "com.vaadin.data.converter.StringToBigDecimalConverter",
      "com.vaadin.ui.declarative.DesignFormatter$4",
      "com.vaadin.ui.declarative.DesignFormatter$5",
      "com.vaadin.ui.declarative.DesignFormatter$6",
      "com.vaadin.ui.declarative.converters.DesignDateConverter",
      "com.vaadin.ui.declarative.converters.DesignLocalDateConverter",
      "com.vaadin.ui.declarative.converters.DesignLocalDateTimeConverter",
      "com.vaadin.ui.declarative.converters.DesignShortcutActionConverter",
      "com.vaadin.ui.declarative.DesignAttributeHandler",
      "com.vaadin.event.Action",
      "com.vaadin.event.ShortcutAction",
      "com.vaadin.event.ShortcutListener",
      "com.vaadin.event.ActionManager",
      "com.vaadin.event.ConnectorActionManager",
      "org.jsoup.select.Elements",
      "com.vaadin.ui.declarative.DesignContext",
      "com.vaadin.event.ConnectorEvent",
      "com.vaadin.server.ClientConnector$DetachEvent",
      "com.vaadin.server.AbstractExtension",
      "com.vaadin.server.Responsive",
      "com.vaadin.server.ServerRpcManager",
      "com.vaadin.ui.Component$Event",
      "com.vaadin.shared.MouseEventDetails$MouseButton",
      "com.vaadin.event.MouseEvents$ClickEvent",
      "com.vaadin.event.ContextClickEvent",
      "com.vaadin.server.ClientConnector$DetachListener",
      "com.vaadin.ui.Component$ErrorEvent",
      "com.vaadin.server.LegacyCommunicationManager",
      "org.jsoup.helper.StringUtil",
      "org.jsoup.nodes.Attribute",
      "org.jsoup.parser.Parser",
      "org.jsoup.parser.HtmlTreeBuilder",
      "org.jsoup.parser.Token$TokenType",
      "org.jsoup.parser.ParseErrorList",
      "org.jsoup.parser.HtmlTreeBuilderState$1",
      "org.jsoup.parser.HtmlTreeBuilderState$2",
      "org.jsoup.parser.HtmlTreeBuilderState$3",
      "org.jsoup.parser.HtmlTreeBuilderState$4",
      "org.jsoup.parser.HtmlTreeBuilderState$5",
      "org.jsoup.parser.HtmlTreeBuilderState$6",
      "org.jsoup.parser.HtmlTreeBuilderState$7",
      "org.jsoup.parser.HtmlTreeBuilderState$8",
      "org.jsoup.parser.HtmlTreeBuilderState$9",
      "org.jsoup.parser.HtmlTreeBuilderState$10",
      "org.jsoup.parser.HtmlTreeBuilderState$11",
      "org.jsoup.parser.HtmlTreeBuilderState$12",
      "org.jsoup.parser.HtmlTreeBuilderState$13",
      "org.jsoup.parser.HtmlTreeBuilderState$14",
      "org.jsoup.parser.HtmlTreeBuilderState$15",
      "org.jsoup.parser.HtmlTreeBuilderState$16",
      "org.jsoup.parser.HtmlTreeBuilderState$17",
      "org.jsoup.parser.HtmlTreeBuilderState$18",
      "org.jsoup.parser.HtmlTreeBuilderState$19",
      "org.jsoup.parser.HtmlTreeBuilderState$20",
      "org.jsoup.parser.HtmlTreeBuilderState$21",
      "org.jsoup.parser.HtmlTreeBuilderState$22",
      "org.jsoup.parser.HtmlTreeBuilderState$23",
      "org.jsoup.parser.HtmlTreeBuilderState",
      "org.jsoup.parser.CharacterReader",
      "org.jsoup.parser.Tokeniser",
      "org.jsoup.parser.TokeniserState$1",
      "org.jsoup.parser.TokeniserState$2",
      "org.jsoup.parser.TokeniserState$3",
      "org.jsoup.parser.TokeniserState$4",
      "org.jsoup.parser.TokeniserState$5",
      "org.jsoup.parser.TokeniserState$6",
      "org.jsoup.parser.TokeniserState$7",
      "org.jsoup.parser.TokeniserState$8",
      "org.jsoup.parser.TokeniserState$9",
      "org.jsoup.parser.TokeniserState$10",
      "org.jsoup.parser.TokeniserState$11",
      "org.jsoup.parser.TokeniserState$12",
      "org.jsoup.parser.TokeniserState$13",
      "org.jsoup.parser.TokeniserState$14",
      "org.jsoup.parser.TokeniserState$15",
      "org.jsoup.parser.TokeniserState$16",
      "org.jsoup.parser.TokeniserState$17",
      "org.jsoup.parser.TokeniserState$18",
      "org.jsoup.parser.TokeniserState$19",
      "org.jsoup.parser.TokeniserState$20",
      "org.jsoup.parser.TokeniserState$21",
      "org.jsoup.parser.TokeniserState$22",
      "org.jsoup.parser.TokeniserState$23",
      "org.jsoup.parser.TokeniserState$24",
      "org.jsoup.parser.TokeniserState$25",
      "org.jsoup.parser.TokeniserState$26",
      "org.jsoup.parser.TokeniserState$27",
      "org.jsoup.parser.TokeniserState$28",
      "org.jsoup.parser.TokeniserState$29",
      "org.jsoup.parser.TokeniserState$30",
      "org.jsoup.parser.TokeniserState$31",
      "org.jsoup.parser.TokeniserState$32",
      "org.jsoup.parser.TokeniserState$33",
      "org.jsoup.parser.TokeniserState$34",
      "org.jsoup.parser.TokeniserState$35",
      "org.jsoup.parser.TokeniserState$36",
      "org.jsoup.parser.TokeniserState$37",
      "org.jsoup.parser.TokeniserState$38",
      "org.jsoup.parser.TokeniserState$39",
      "org.jsoup.parser.TokeniserState$40",
      "org.jsoup.parser.TokeniserState$41",
      "org.jsoup.parser.TokeniserState$42",
      "org.jsoup.parser.TokeniserState$43",
      "org.jsoup.parser.TokeniserState$44",
      "org.jsoup.parser.TokeniserState$45",
      "org.jsoup.parser.TokeniserState$46",
      "org.jsoup.parser.TokeniserState$47",
      "org.jsoup.parser.TokeniserState$48",
      "org.jsoup.parser.TokeniserState$49",
      "org.jsoup.parser.TokeniserState$50",
      "org.jsoup.parser.TokeniserState$51",
      "org.jsoup.parser.TokeniserState$52",
      "org.jsoup.parser.TokeniserState$53",
      "org.jsoup.parser.TokeniserState$54",
      "org.jsoup.parser.TokeniserState$55",
      "org.jsoup.parser.TokeniserState$56",
      "org.jsoup.parser.TokeniserState$57",
      "org.jsoup.parser.TokeniserState$58",
      "org.jsoup.parser.TokeniserState$59",
      "org.jsoup.parser.TokeniserState$60",
      "org.jsoup.parser.TokeniserState$61",
      "org.jsoup.parser.TokeniserState$62",
      "org.jsoup.parser.TokeniserState$63",
      "org.jsoup.parser.TokeniserState$64",
      "org.jsoup.parser.TokeniserState$65",
      "org.jsoup.parser.TokeniserState$66",
      "org.jsoup.parser.TokeniserState$67",
      "org.jsoup.parser.TokeniserState",
      "org.jsoup.parser.HtmlTreeBuilderState$24",
      "com.vaadin.server.Sizeable$Unit"
    );
  }
}
