/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 05 21:47:51 GMT 2018
 */

package com.polimi.travlendar.gmaps;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.google.maps.model.DirectionsResult;
import com.google.maps.model.PlacesSearchResult;
import com.polimi.travlendar.gmaps.LocationForm;
import com.polimi.travlendar.gmaps.PlaceSearchField;
import com.vaadin.ui.Button;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LocationForm_ESTest extends LocationForm_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LocationForm locationForm0 = new LocationForm();
      PlaceSearchField placeSearchField0 = new PlaceSearchField();
      locationForm0.deliverPlace(placeSearchField0, (PlacesSearchResult) null);
      assertTrue(placeSearchField0.isVisible());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LocationForm locationForm0 = new LocationForm();
      PlaceSearchField placeSearchField0 = locationForm0.start;
      PlacesSearchResult placesSearchResult0 = new PlacesSearchResult();
      // Undeclared exception!
      try { 
        locationForm0.deliverPlace(placeSearchField0, placesSearchResult0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.polimi.travlendar.gmaps.VaadinMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LocationForm locationForm0 = new LocationForm();
      PlaceSearchField placeSearchField0 = locationForm0.end;
      PlacesSearchResult placesSearchResult0 = new PlacesSearchResult();
      // Undeclared exception!
      try { 
        locationForm0.deliverPlace(placeSearchField0, placesSearchResult0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.polimi.travlendar.gmaps.VaadinMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LocationForm locationForm0 = new LocationForm();
      Button button0 = locationForm0.getSubmit();
      assertTrue(button0.isVisible());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LocationForm locationForm0 = new LocationForm();
      // Undeclared exception!
      try { 
        locationForm0.resultNotFoundError();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.vaadin.ui.Notification", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LocationForm locationForm0 = new LocationForm();
      DirectionsResult directionsResult0 = locationForm0.getDirections();
      assertNull(directionsResult0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      LocationForm locationForm0 = new LocationForm();
      PlacesSearchResult placesSearchResult0 = locationForm0.getEndPlace();
      assertNull(placesSearchResult0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      LocationForm locationForm0 = new LocationForm();
      PlacesSearchResult placesSearchResult0 = locationForm0.getStartPlace();
      assertNull(placesSearchResult0);
  }
}
