/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 05 22:14:20 GMT 2018
 */

package com.polimi.travlendar.frontend.ui.pages.gmaps;

import org.junit.Test;
import static org.junit.Assert.*;
import com.polimi.travlendar.frontend.ui.pages.gmaps.MapsPage;
import com.vaadin.navigator.ViewChangeListener;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MapsPage_ESTest extends MapsPage_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MapsPage mapsPage0 = new MapsPage();
      mapsPage0.enter((ViewChangeListener.ViewChangeEvent) null);
      assertTrue(mapsPage0.isVisible());
  }
}
