/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 05 22:25:22 GMT 2018
 */

package com.polimi.travlendar.frontend.ui.pages.gmaps;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.MockitoExtension.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.polimi.travlendar.frontend.ui.pages.gmaps.MapsAddOnPage;
import com.vaadin.navigator.ViewChangeListener;
import com.vaadin.ui.Alignment;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MapsAddOnPage_ESTest extends MapsAddOnPage_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MapsAddOnPage mapsAddOnPage0 = new MapsAddOnPage();
      mapsAddOnPage0.setDefaultComponentAlignment((Alignment) null);
      ViewChangeListener.ViewChangeEvent viewChangeListener_ViewChangeEvent0 = mock(ViewChangeListener.ViewChangeEvent.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        mapsAddOnPage0.enter(viewChangeListener_ViewChangeEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.vaadin.ui.AbstractOrderedLayout", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MapsAddOnPage mapsAddOnPage0 = new MapsAddOnPage();
      ViewChangeListener.ViewChangeEvent viewChangeListener_ViewChangeEvent0 = mock(ViewChangeListener.ViewChangeEvent.class, new ViolatedAssumptionAnswer());
      mapsAddOnPage0.enter(viewChangeListener_ViewChangeEvent0);
      assertTrue(mapsAddOnPage0.isVisible());
  }
}
