/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 05 22:31:18 GMT 2018
 */

package com.polimi.travlendar.payment.checkout;

import org.junit.Test;
import static org.junit.Assert.*;
import com.polimi.travlendar.payment.checkout.CheckoutJs;
import com.polimi.travlendar.payment.checkout.CheckoutJsLabelState;
import com.vaadin.server.Sizeable;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CheckoutJs_ESTest extends CheckoutJs_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CheckoutJs checkoutJs0 = new CheckoutJs((String) null, "");
      String string0 = checkoutJs0.getUser();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CheckoutJs checkoutJs0 = new CheckoutJs("", "");
      String string0 = checkoutJs0.getUser();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CheckoutJs checkoutJs0 = new CheckoutJs("[00VY", "[00VY");
      CheckoutJsLabelState checkoutJsLabelState0 = checkoutJs0.getState();
      assertTrue(checkoutJsLabelState0.enabled);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CheckoutJs checkoutJs0 = new CheckoutJs("eb]NaB", "eb]NaB");
      checkoutJs0.setKey((String) null);
      String string0 = checkoutJs0.getKey();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CheckoutJs checkoutJs0 = new CheckoutJs("~", "VpQX");
      checkoutJs0.setKey("");
      String string0 = checkoutJs0.getKey();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CheckoutJs checkoutJs0 = new CheckoutJs((String) null, (String) null);
      String string0 = checkoutJs0.getAmount();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CheckoutJs checkoutJs0 = new CheckoutJs("", "");
      String string0 = checkoutJs0.getAmount();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CheckoutJs checkoutJs0 = new CheckoutJs("", "");
      checkoutJs0.setAmount("");
      assertEquals(Sizeable.Unit.PIXELS, checkoutJs0.getWidthUnits());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CheckoutJs checkoutJs0 = new CheckoutJs("", "");
      checkoutJs0.setUser("");
      assertEquals((-1.0F), checkoutJs0.getHeight(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CheckoutJs checkoutJs0 = new CheckoutJs("eb]NaB", "eb]NaB");
      String string0 = checkoutJs0.getAmount();
      assertEquals("eb]NaB", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CheckoutJs checkoutJs0 = new CheckoutJs("~", "VpQX");
      String string0 = checkoutJs0.getKey();
      assertEquals("pk_test_Br0eRZUzudfg2GZQWZVAJxju", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CheckoutJs checkoutJs0 = new CheckoutJs("~", "VpQX");
      String string0 = checkoutJs0.getUser();
      assertEquals("~", string0);
  }
}
