/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 04 11:30:22 GMT 2018
 */

package com.polimi.travlendar.frontend.ui.pages;

import org.junit.Test;
import static org.junit.Assert.*;
import com.polimi.travlendar.frontend.ui.pages.ErrorView;
import com.vaadin.navigator.ViewChangeListener;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ErrorView_ESTest extends ErrorView_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ErrorView errorView0 = new ErrorView();
      errorView0.enter((ViewChangeListener.ViewChangeEvent) null);
      assertTrue(errorView0.isVisible());
  }
}
