/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 04 11:13:09 GMT 2018
 */

package com.polimi.travlendar.backend.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.polimi.travlendar.backend.beans.StripeService;
import com.polimi.travlendar.payment.checkout.ChargeRequest;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class StripeService_ESTest extends StripeService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      StripeService stripeService0 = new StripeService();
      ChargeRequest chargeRequest0 = new ChargeRequest();
      // Undeclared exception!
      try { 
        stripeService0.charge(chargeRequest0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.polimi.travlendar.backend.beans.StripeService", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      StripeService stripeService0 = new StripeService();
      // Undeclared exception!
      try { 
        stripeService0.stripeInit("_#4n@jziYgFA&Sn#.");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.polimi.travlendar.backend.beans.StripeService", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      StripeService stripeService0 = new StripeService();
      stripeService0.init();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      StripeService stripeService0 = new StripeService();
      // Undeclared exception!
      try { 
        stripeService0.getBalance();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.polimi.travlendar.backend.beans.StripeService", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      StripeService stripeService0 = new StripeService();
      // Undeclared exception!
      try { 
        stripeService0.updateBalance((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.polimi.travlendar.backend.beans.StripeService", e);
      }
  }
}
