/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 05 22:21:17 GMT 2018
 */

package com.polimi.travlendar.gmaps;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.polimi.travlendar.gmaps.DefaultCaptionGenerator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DefaultCaptionGenerator_ESTest extends DefaultCaptionGenerator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultCaptionGenerator defaultCaptionGenerator0 = new DefaultCaptionGenerator();
      // Undeclared exception!
      try { 
        defaultCaptionGenerator0.apply((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DefaultCaptionGenerator defaultCaptionGenerator0 = new DefaultCaptionGenerator();
      Object object0 = new Object();
      String string0 = defaultCaptionGenerator0.apply(object0);
      assertNotNull(string0);
  }
}
