/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 05 22:20:09 GMT 2018
 */

package com.polimi.travlendar.gmaps;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.google.maps.model.AutocompletePrediction;
import com.polimi.travlendar.gmaps.PredictionCaptionGenerator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PredictionCaptionGenerator_ESTest extends PredictionCaptionGenerator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PredictionCaptionGenerator predictionCaptionGenerator0 = new PredictionCaptionGenerator();
      AutocompletePrediction autocompletePrediction0 = new AutocompletePrediction();
      autocompletePrediction0.description = "zj\"";
      String string0 = predictionCaptionGenerator0.apply(autocompletePrediction0);
      assertEquals("zj\"", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PredictionCaptionGenerator predictionCaptionGenerator0 = new PredictionCaptionGenerator();
      AutocompletePrediction autocompletePrediction0 = new AutocompletePrediction();
      autocompletePrediction0.description = "";
      String string0 = predictionCaptionGenerator0.apply(autocompletePrediction0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PredictionCaptionGenerator predictionCaptionGenerator0 = new PredictionCaptionGenerator();
      // Undeclared exception!
      try { 
        predictionCaptionGenerator0.apply((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.polimi.travlendar.gmaps.PredictionCaptionGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PredictionCaptionGenerator predictionCaptionGenerator0 = new PredictionCaptionGenerator();
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        predictionCaptionGenerator0.apply(object0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Object cannot be cast to com.google.maps.model.AutocompletePrediction
         //
         verifyException("com.polimi.travlendar.gmaps.PredictionCaptionGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      PredictionCaptionGenerator predictionCaptionGenerator0 = new PredictionCaptionGenerator();
      AutocompletePrediction autocompletePrediction0 = new AutocompletePrediction();
      String string0 = predictionCaptionGenerator0.apply(autocompletePrediction0);
      assertNull(string0);
  }
}
