/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 04 11:30:05 GMT 2018
 */

package com.polimi.travlendar.gmaps;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.polimi.travlendar.gmaps.PredictionCaptionGenerator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PredictionCaptionGenerator_ESTest extends PredictionCaptionGenerator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PredictionCaptionGenerator predictionCaptionGenerator0 = new PredictionCaptionGenerator();
      // Undeclared exception!
      try { 
        predictionCaptionGenerator0.apply(predictionCaptionGenerator0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // com.polimi.travlendar.gmaps.PredictionCaptionGenerator cannot be cast to com.google.maps.model.AutocompletePrediction
         //
         assertThrownBy("com.polimi.travlendar.gmaps.PredictionCaptionGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PredictionCaptionGenerator predictionCaptionGenerator0 = new PredictionCaptionGenerator();
      // Undeclared exception!
      try { 
        predictionCaptionGenerator0.apply((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.polimi.travlendar.gmaps.PredictionCaptionGenerator", e);
      }
  }
}
